#!/usr/bin/env python3
"""Regenerate docs/tour/site/js/content.js from bw.c + docs/tour/stations/*.md.

Usage:
  python3 tools/gen_content.py           # regenerate js/content.js
  python3 tools/gen_content.py --check   # verify the committed copy matches the sources

The generated file is checked in: the site itself is static (no build step, runs
from file://) and loads the content via <script src>. The generator exists so a
station edit needs one command, not a hand-edit of the JS blob.

The partition (docs/tour/partition.md, ticket #24) pins bw.c to the blob
8db1861...; --check enforces that the working-tree bw.c still matches, so the
station line ranges stay anchored to the right source.
"""

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
BW_C = ROOT / "bw.c"
STATIONS_DIR = ROOT / "docs" / "tour" / "stations"
OUT = ROOT / "docs" / "tour" / "site" / "js" / "content.js"

PINNED_BW_BLOB = "8db18617ff8e69026dbe0502fc438e5b34d89fd4"


def git_blob_sha1(data: bytes) -> str:
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def load_source() -> str:
    """bw.c as the pinned blob: LF-normalized, verified against the partition's
    pinned blob id (the working tree may carry CRLF; git stores LF)."""
    data = BW_C.read_bytes().replace(b"\r\n", b"\n")
    blob = git_blob_sha1(data)
    if blob != PINNED_BW_BLOB:
        raise SystemExit(
            "bw.c has moved off the pinned blob %s (now %s). The partition's "
            "station line ranges are anchored to the pinned file; re-anchor "
            "the partition (docs/tour/partition.md) before regenerating."
            % (PINNED_BW_BLOB, blob)
        )
    return data.decode("utf-8")


def load_stations():
    files = sorted(STATIONS_DIR.glob("[0-9][0-9]-*.md")) + [
        STATIONS_DIR / "capstone.md"
    ]
    stations = []
    for f in files:
        text = f.read_text(encoding="utf-8").replace("\r\n", "\n")
        if text.startswith("﻿"):
            text = text[1:]
        stations.append({"file": f.name, "text": text})
    return stations


def build_js(source: str, stations) -> str:
    def js_str(s: str) -> str:
        return json.dumps(s, ensure_ascii=False)

    lines = [
        "/* GENERATED by tools/gen_content.py — do not edit by hand.",
        "   Regenerate: python3 tools/gen_content.py   (verify: --check)",
        "   Sources: bw.c (pinned blob %s) and docs/tour/stations/*.md"
        % PINNED_BW_BLOB,
        "   Station files are markdown-ish text parsed at runtime by js/app.js",
        "   (see docs/tour/stations/README.md — the renderer contract).",
        "*/",
        "const TOUR_CONTENT = {",
        '  "source": %s,' % js_str(source),
        '  "stations": [',
    ]
    for i, st in enumerate(stations):
        comma = "," if i + 1 < len(stations) else ""
        lines.append('    {"file": %s, "text": %s}%s'
                     % (js_str(st["file"]), js_str(st["text"]), comma))
    lines.append("  ]")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    source = load_source()
    stations = load_stations()
    js = build_js(source, stations)

    if check:
        try:
            cur = OUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            cur = None
        if cur != js:
            raise SystemExit(
                "content.js is out of sync (%d stations, %d source lines). "
                "Regenerate: python3 tools/gen_content.py"
                % (len(stations), source.count("\n"))
            )
        print("content.js in sync: %d stations, %d source lines, bw.c on the "
              "pinned blob." % (len(stations), source.count("\n")))
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js, encoding="utf-8")
    print("wrote %s: %d stations, %d source lines, %.1f KB"
          % (OUT, len(stations), source.count("\n"), len(js.encode()) / 1024))


if __name__ == "__main__":
    main()
