/*
 * Teaching app — shared content model.
 *
 * Every stop carries the same four layers: concept / annotated code / ADR why /
 * viva what-ifs. The three prototype variants (A: field notes, B: system map,
 * C: viva deck) render this one model three structurally-different ways.
 *
 * Vocabulary follows CONTEXT.md. Code snippets are verbatim from bw.c with
 * inline comments elided where the gutter annotation carries them.
 */
window.APP = {
  title: "bw.c — follow the data",
  subtitle: "Verbs API throughput benchmark, end to end",

  home: {
    lead: "One client, one server, one queue pair, 21 message sizes. The client streams RDMA WRITEs into the server's registered memory and measures how fast they land — the clock runs from the first timed post until the server's ack arrives.",
    roles: [
      { who: "Client", what: "Drives everything: posts the WRITEs, starts and stops the clock, prints the 21 result lines." },
      { who: "Server", what: "Absorbs the WRITEs into its 1 MB buffer and acks each size's done. Its only data-path job." },
      { who: "The QP", what: "One Reliable Connected queue pair carries the data WRITEs AND the control messages (done / ack) as SENDs — the only QP in the program." },
      { who: "The window", what: "Up to W = 256 WRITEs outstanding at once, completions accounted in batches of K = 64. The pipe never drains." },
    ],
    highlights: [
      { value: "21", label: "sizes, 1 B to 1 MB, powers of two" },
      { value: "42.6", label: "Gbps peak (64 KB, mlxstud03/04)" },
      { value: "6.1M", label: "messages/s at small sizes" },
      { value: "W=256 · K=64", label: "the measured optimum (ADR-0006/0007)" },
    ],
  },

  /* The whole spine. state: 'built' (has a full stop) or 'planned'. */
  spine: [
    { id: "experiment", group: "Setup", title: "The experiment", state: "built" },
    { id: "handshake", group: "Setup", title: "The handshake", state: "built" },
    { id: "memory-region", group: "Setup", title: "Memory region", state: "built" },
    { id: "posting", group: "Data path", title: "Posting the window", state: "built" },
    { id: "doorbell", group: "Data path", title: "The doorbell", state: "planned" },
    { id: "wire", group: "Data path", title: "On the wire", state: "planned" },
    { id: "landing", group: "Data path", title: "Landing in server memory", state: "planned" },
    { id: "completions", group: "Data path", title: "Completions", state: "planned" },
    { id: "envelope", group: "The envelope", title: "The shape of the numbers", state: "planned" },
    { id: "audit", group: "Inside the audit", title: "What the audit found", state: "planned" },
    { id: "viva", group: "Viva", title: "Mock oral exam", state: "planned" },
  ],

  /* The measured envelope: means of 3 default sweeps, mlxstud03/04 (ADR-0007). */
  envelope: {
    unit: "Gbps",
    series: [
      { size: 0, bytes: 1, gbps: 0.049 },
      { size: 1, bytes: 2, gbps: 0.098 },
      { size: 2, bytes: 4, gbps: 0.196 },
      { size: 3, bytes: 8, gbps: 0.392 },
      { size: 4, bytes: 16, gbps: 0.784 },
      { size: 5, bytes: 32, gbps: 1.56 },
      { size: 6, bytes: 64, gbps: 2.62 },
      { size: 7, bytes: 128, gbps: 3.577 },
      { size: 8, bytes: 256, gbps: 5.84 },
      { size: 9, bytes: 512, gbps: 6.29 },
      { size: 10, bytes: 1024, gbps: 6.55 },
      { size: 11, bytes: 2048, gbps: 32.67 },
      { size: 12, bytes: 4096, gbps: 42.36 },
      { size: 13, bytes: 8192, gbps: 42.37 },
      { size: 14, bytes: 16384, gbps: 42.46 },
      { size: 15, bytes: 32768, gbps: 42.5 },
      { size: 16, bytes: 65536, gbps: 42.3 },
      { size: 17, bytes: 131072, gbps: 42.04 },
      { size: 18, bytes: 262144, gbps: 41.53 },
      { size: 19, bytes: 524288, gbps: 41.55 },
      { size: 20, bytes: 1048576, gbps: 40.57 },
    ],
  },

  stops: {
    experiment: {
      id: "experiment",
      title: "The experiment",
      subtitle: "What one size of the sweep measures, and where the clock sits",
      group: "Setup",
      adrs: ["0003"],
      concept: [
        "The benchmark is one number: how many bytes per second the client can push into the server's memory over one RC QP. It is measured once per size — 1 B through 1 MB, powers of two — because 'throughput' is not one number: at 1 B it is a message-rate story (6.1M messages/s), at 1 MB it is a wire story (40.6 Gbps).",
        "Each size is measured as two batches: a small warmup batch, then the timed batch whose elapsed time defines the number. The warmup rides the same windowed stream ahead of the timed batch so the pipe is already full when the clock starts.",
        "The clock (CLOCK_MONOTONIC) starts immediately before the first timed WRITE is posted and stops when the ack is received — the entire batch plus the control round trip is inside the measured window. Output is one ex1-identical line per size: size, throughput, unit.",
      ],
      terms: [
        { term: "Timed batch", def: "the MSG_COUNTS[i] WRITEs of one size whose elapsed time defines the throughput" },
        { term: "Warmup batch", def: "WARMUP_COUNTS[i] WRITEs sent before the timed batch, pipelined with it" },
        { term: "Size sweep", def: "the 21 sizes measured in one run, ascending; one warmup + timed batch per size" },
        { term: "Counts table", def: "per-size message counts inherited from ex1's convergence experiments (<1% variance between doubled counts)" },
        { term: "Done / Ack", def: "the two control SENDs per size: the done closes the timed batch, the ack carries the completion barrier back" },
        { term: "Sequence counter", def: "the size index 0–20 carried by both control messages; a mismatch means the exchange desynchronized" },
      ],
      code: {
        heading: "bw_client_bench — one size of the sweep",
        file: "bw.c:992–1021",
        lines: [
          "for (seq = 0; seq < SWEEP_SIZES; ++seq) {",
          "    size_t size = (size_t) 1 << seq;",
          "    uint64_t count = count_override ? count_override : MSG_COUNTS[seq];",
          "    struct bw_ctrl_msg done = { .tag = BW_CTRL_TAG, .seq = seq };",
          "",
          "    if (bw_post_writes(ctx, dest, size, WARMUP_COUNTS[seq],",
          "                       window, k, wrs, sges, &st, 0))",
          "        goto out;",
          "",
          "    clock_gettime(CLOCK_MONOTONIC, &t0);",
          "",
          "    if (bw_post_writes(ctx, dest, size, count,",
          "                       window, k, wrs, sges, &st, 1))",
          "        goto out;",
          "",
          "    if (bw_post_ctrl_send(ctx, BW_SEND_DONE_WRID, &done))",
          "        goto out;",
          "",
          "    if (bw_recv_ctrl(ctx,",
          "                     (1ull << BW_SEND_DONE_WRID) | (1ull << BW_DATA_WRID),",
          "                     seq, \"Ack\", &t1))",
          "        goto out;",
          "",
          "    elapsed = (double) (t1.tv_sec - t0.tv_sec) +",
          "              (double) (t1.tv_nsec - t0.tv_nsec) / 1e9;",
          "    bw_print_result(size, count, elapsed);",
          "}",
        ],
        annotations: {
          1: "21 sizes, ascending: size = 2^seq, so 2^0 = 1 B … 2^20 = 1 MB. seq doubles as the sequence counter.",
          2: "The counts table: ex1's converged numbers, verbatim (1 B: 1,310,720 WRITEs → 64 KB: 2560 → 1 MB: 80).",
          3: "The done control message — 8 bytes: tag + sequence counter. Sent on the data QP, never over TCP (ADR-0001).",
          5: "Warmup batch first: 4–32 WRITEs ride the stream ahead of the timed batch. It fills the pipe … at these counts, only partway — the audit's one methodology nuance.",
          8: "t0: the clock starts AFTER the warmup, immediately before the first timed post. Nothing before this counts.",
          10: "The timed batch: the WRITEs that define the number. Same windowed stream — the warmup and timed batches are one continuous pipe.",
          13: "The done SEND: 'all my timed WRITEs are posted'. RC in-order delivery means the server's done-receive completion proves every prior WRITE has landed.",
          15: "The ack wait: the clock stops HERE, at the ack's receive completion — not at the last post. The ack is the completion barrier (ADR-0003).",
          16: "While waiting for the ack, the data and done-send completions pass through — they precede the ack in the CQ, in order.",
          18: "Elapsed = ack time − first-post time: the whole batch plus the control round trip is inside the measured window.",
          20: "One ex1-identical line: size, throughput (auto-scaled bps → Gbps), nothing else. Byte-identical output to the TCP exercise.",
        },
      },
      why: [
        {
          adr: "ADR-0003",
          title: "Why the clock runs until the ack arrives",
          text: "A client-side completion only means the HCA sent the message — not that the server's memory holds it. Stopping the clock at the last WRITE post would measure the local enqueue rate, a different quantity, and the assignment's warning exists because students overstate throughput that way. The ack is a true completion barrier: it can only arrive after the server received the done, which in-order RC delivery guarantees came after every WRITE. Cost: one control round trip (~10 µs) added to every size — negligible above 1-byte, identical in shape for all.",
        },
        {
          adr: "ADR-0003",
          title: "Why it mirrors ex1 exactly",
          text: "The clock window is the same as the TCP exercise's ('the clock runs until the ACK arrives'), which keeps the output class-comparable: same methodology, same 21 lines, so the two exercises' numbers can sit side by side (and the IB numbers beat ex1's 1 GbE numbers ~7×).",
        },
        {
          adr: "ADR-0003",
          title: "A consequence: the server is on the client's clock",
          text: "Because the ack is inside the window, a slow server directly inflates every measurement. That is by design — it is what 'the message actually arrived' means — but it means the server's ack path is part of the measured quantity, and it is why the server acks each done before waiting for the next.",
        },
      ],
      whatifs: [
        {
          q: "What if the clock stopped at the last WRITE post instead?",
          a: "It would measure the local post rate, not the wire. At DMA sizes the enqueue rate outruns the link, so everything still in flight at t1 (up to W = 256 WRITEs, ~1.5 MB) would be counted as already delivered — the number would overstate the true rate by the inflight window's worth of bytes. The audit's rule of thumb: a completion means sent, not received.",
        },
        {
          q: "What if each side timed itself (two clocks)?",
          a: "You would measure a different quantity than ex1, and the two halves would need synchronization and a decision about where one ends and the other begins. Keeping one clock on the client, from first post to ack, reproduces ex1's methodology exactly — the property the assignment's output contract and ADR-0003 exist to preserve.",
        },
        {
          q: "What if there were no warmup batch?",
          a: "The pipe would start empty: the timed batch would spend its first ~256 WRITEs ramping the window up instead of saturating the wire. At 1 MB (80 WRITEs) the ramp would be the whole batch — the measured 1 MB dip is partly this arithmetic: rate = R·n/(n+4), 80/84 at n = 80, predicting 40.54 Gbps against the measured 40.57. The research ticket proposed a warmup ≥ W as an optimization lead (~1.76 Gbps recoverable at 1 MB).",
        },
        {
          q: "What if the ack were a TCP message instead?",
          a: "The done would be delivered out of order with respect to the WRITEs, so the ack could arrive while the last WRITEs are still on the wire — the clock would stop early and throughput would be overstated. That is why ADR-0001 chose SENDs on the data QP for both control messages.",
        },
      ],

      /* Frames — one idea per screen: code (top-left), explanation
       * (bottom-left), diagram (right, synced to the frame). */
      frames: [
        {
          id: "run", title: "The run at a glance",
          diagram: "connection",
          explain: [
            "Two processes, one RC queue pair, one direction of traffic. The client drives everything: it posts the WRITEs, runs the clock, prints the results. The server's only data-path job is absorbing WRITEs into its registered 1 MB buffer.",
            "The QP is the whole link: data WRITEs AND the two control messages per size ride it. TCP exists only for the one-time handshake — LID/QPN/PSN/GID plus the server's buffer address and rkey.",
          ],
          why: {
            adr: "0001",
            title: "Why control messages ride the data QP",
            text: "The ack must be a true barrier: RC in-order delivery means it can only arrive after every prior WRITE landed in server memory. Over TCP it would not be ordered against the WRITEs, and the clock could stop early.",
          },
        },
        {
          id: "batches", title: "One size, two batches",
          code: {
            file: "bw.c:1000–1011",
            lines: [
              "if (bw_post_writes(ctx, dest, size, WARMUP_COUNTS[seq],",
              "                   window, k, wrs, sges, &st, 0))",
              "    goto out;",
              "",
              "clock_gettime(CLOCK_MONOTONIC, &t0);",
              "",
              "if (bw_post_writes(ctx, dest, size, count,",
              "                   window, k, wrs, sges, &st, 1))",
              "    goto out;",
            ],
            annotations: {
              1: "Warmup first: 4–32 WRITEs ride the stream ahead of the timed batch, so the pipe is already flowing when the clock starts.",
              5: "t0 — the clock starts AFTER the warmup, immediately before the first timed post. Nothing before it counts.",
              7: "The timed batch: the WRITEs whose elapsed time defines the number.",
            },
          },
          diagram: "timeline",
          explain: [
            "Every size gets two batches on one continuous windowed stream. The warmup is small (4–32 WRITEs, inherited from ex1) — its job is to have the pipe moving at t0, not to be measured.",
            "The timed batch is the size's count from the counts table — 1,310,720 WRITEs at 1 B down to 80 at 1 MB. Its elapsed time becomes the throughput number.",
          ],
        },
        {
          id: "counts", title: "The counts table",
          code: {
            file: "bw.c:105–121",
            lines: [
              "#define SWEEP_SIZES 21",
              "",
              "static const uint64_t MSG_COUNTS[SWEEP_SIZES] = {",
              "        1310720, 81920, 655360, 163840, 327680, /* 1B 2B 4B 8B 16B */",
              "        20480, 81920, 81920, 40960, 20480,      /* 32B 64B 128B 256B 512B */",
              "        20480, 20480, 20480, 2560, 2560,        /* 1KB 2KB 4KB 8KB 16KB */",
              "        2560, 640, 320, 160, 160,               /* 32KB 64KB 128KB 256KB 512KB */",
              "        80                                       /* 1MB */",
              "};",
              "",
              "static const uint64_t WARMUP_COUNTS[SWEEP_SIZES] = {",
              "        16, 4, 4, 32, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4",
              "};",
            ],
            annotations: {
              1: "21 = the size sweep, 2^0 = 1 B … 2^20 = 1 MB. The same constant bounds the sequence counter (0–20) — the loop and the table can never drift apart.",
              3: "The timed counts: how many WRITEs of each size define that size's number. At 1 B it takes 1,310,720 — the message-rate regime.",
              7: "Counts fall as sizes rise: 64 KB needs only 2,560 WRITEs to fill the pipe long enough to measure stably.",
              8: "80 WRITEs at 1 MB — the wire regime. Every batch lasts ≥ ~16 ms: far above timer resolution, far below the verify script's 180 s budget (audit).",
              11: "The warmup counts: 4–32 WRITEs per size, ALL below the window W = 256. At t0 the pipe is therefore not full — the audit's one methodology nuance; the table is verbatim ex1's, so the methodology matches ex1 exactly (ADR-0003).",
            },
          },
          diagram: "counts-table",
          explain: [
            "The counts were not chosen by this project — they are ex1's converged table, verbatim. ex1 found each count by doubling until throughput stopped changing (< 1% variance between doubled counts): the smallest batch that measures the number stably.",
            "The shape follows the physics: at small sizes throughput is a message-rate story, so it takes a million WRITEs to average out; at 1 MB the messages are so heavy that 80 suffice.",
          ],
          whatif: {
            q: "What if one count were too small?",
            a: "The batch would be dominated by ramp-up and noise — the number would wobble run to run. That is exactly what ex1's convergence method was for: double the count until the variance is gone. Too large and the sweep drags past the verify script's budget — the converged table is the smallest stable count per size.",
          },
        },
        {
          id: "clock", title: "The clock window",
          code: {
            file: "bw.c:1004–1019",
            lines: [
              "clock_gettime(CLOCK_MONOTONIC, &t0);",
              "",
              "if (bw_recv_ctrl(ctx, (1ull << BW_SEND_DONE_WRID)",
              "                     | (1ull << BW_DATA_WRID), seq, \"Ack\", &t1))",
              "    goto out;",
              "",
              "elapsed = (double) (t1.tv_sec - t0.tv_sec) +",
              "          (double) (t1.tv_nsec - t0.tv_nsec) / 1e9;",
            ],
            annotations: {
              1: "t0: before the first timed post.",
              3: "t1: the ack's receive completion — the clock stops HERE, not at the last post.",
              4: "While waiting, the data and done-send completions pass through — they precede the ack in the CQ, in order.",
              6: "Elapsed = ack time − first-post time. The whole batch plus the control round trip is inside the measured window.",
            },
          },
          diagram: "clock-window",
          explain: [
            "The measured window is one interval: from the first timed post to the ack's arrival. Why the ack and not the last post? Because a client-side completion only means the HCA sent the message — not that the server's memory holds it.",
            "The ack is the completion barrier (ADR-0003): RC in-order delivery means the server received the done only after every prior WRITE, and the ack carries that guarantee back. Cost: one ~10 µs control round trip per size — negligible above 1 byte, identical in shape for all.",
          ],
          why: {
            adr: "0003",
            title: "Why ex1's methodology is preserved",
            text: "Same window as the TCP exercise ('the clock runs until the ACK arrives') — byte-identical output, class-comparable numbers, and the IB numbers beat ex1's 1 GbE results ~7×.",
          },
        },
        {
          id: "controls", title: "Done and ack",
          code: {
            file: "bw.c:1010–1016",
            lines: [
              "if (bw_post_ctrl_send(ctx, BW_SEND_DONE_WRID, &done))",
              "    goto out;",
              "",
              "if (bw_recv_ctrl(ctx,",
              "                 (1ull << BW_SEND_DONE_WRID) | (1ull << BW_DATA_WRID),",
              "                 seq, \"Ack\", &t1))",
              "    goto out;",
            ],
            annotations: {
              1: "The done SEND, always signaled: 'all my timed WRITEs are posted'. 8 bytes — tag + sequence counter.",
              4: "The ack wait: the server's reply, also on the data QP.",
              6: "seq is the size index 0–20; a mismatch means the exchange desynchronized and the run aborts.",
            },
          },
          diagram: "control-flow",
          explain: [
            "Per size, exactly two control messages — the only SENDs in the run besides the data WRITEs. The done closes the timed batch; the ack echoes its sequence counter back.",
            "The server verifies the done's seq before acking; the client verifies the ack's. Both messages carry the fixed tag 0x4354524c and the sequence counter, so a desync fails loudly instead of corrupting numbers.",
          ],
          whatif: {
            q: "What if the ack were a TCP message?",
            a: "It would not be ordered against the WRITEs — it could arrive while the last ones are still on the wire, and the clock would stop early. That is exactly why ADR-0001 put both control messages on the data QP.",
          },
        },
        {
          id: "ctrl-msg", title: "The control message — 8 bytes",
          code: {
            file: "bw.c:123–133",
            lines: [
              "/* Control messages: 8 bytes each — a fixed tag plus the sequence counter",
              " * (the size index 0..20). The ack carries the received done verbatim, so",
              " * a tag or sequence mismatch means the exchange desynchronized. */",
              "#define BW_CTRL_TAG 0x4354524cu",
              "struct bw_ctrl_msg {",
              "    uint32_t tag;",
              "    uint32_t seq;",
              "};",
              "",
              "/* The control message must always fit one inline send. */",
              "typedef char bw_ctrl_msg_size[(sizeof (struct bw_ctrl_msg) == 8) ? 1 : -1];",
            ],
            annotations: {
              4: "The tag 0x4354524c spells 'CTRL' in ASCII (0x43 = C, 0x54 = T, 0x52 = R, 0x4c = L) — a fixed signature every control message carries.",
              5: "The whole message: two uint32s. tag proves it is a control message, seq proves it is for THIS size.",
              7: "seq: the size index 0–20. The ack echoes the done's seq, so a mismatch means the exchange desynchronized — abort, never print corrupt numbers.",
              11: "The sizeof assert: if the struct ever grew past 8 bytes, this typedef of a negative-sized array makes the BUILD fail — before the run. The message must always fit one inline send.",
            },
          },
          diagram: "ctrl-msg",
          explain: [
            "Every control message — done or ack — is exactly this: 8 bytes. Two halves: the tag that says 'I am a control message', and the sequence counter that says 'I belong to size i'.",
            "Both sides verify both halves of every message they receive. The wr_id taxonomy routes completions; the tag and seq validate the payload — a corrupted or desynced exchange fails loudly instead of printing bad numbers.",
          ],
          why: {
            adr: "0001",
            title: "Why a tag at all",
            text: "The wr_id tells the poll loop WHICH kind of completion arrived; the tag tells it the MESSAGE is the right one. RC guarantees delivery order, not content integrity — the fixed tag is the cheap guard that turns a desynced exchange into an error instead of corrupt numbers.",
          },
        },
        {
          id: "result", title: "The result line",
          code: {
            file: "bw.c:953–965",
            lines: [
              "static void bw_print_result(size_t size, uint64_t count, double elapsed) {",
              "    double bps = (double) size * (double) count * 8.0 / elapsed;",
              "    if (bps < 1000.0)      printf(\"%zu\\t%.2f\\t%s\\n\", size, bps, \"bps\");",
              "    else if (bps < 1000000.0)  printf(\"%zu\\t%.2f\\t%s\\n\", size, bps / 1000.0, \"Kbps\");",
              "    else if (bps < 1000000000.0) printf(\"%zu\\t%.2f\\t%s\\n\", size, bps / 1000000.0, \"Mbps\");",
              "    else                 printf(\"%zu\\t%.2f\\t%s\\n\", size, bps / 1000000000.0, \"Gbps\");",
              "}",
            ],
            annotations: {
              1: "bytes × count × 8 bits ÷ seconds — the throughput definition.",
              2: "Units auto-scale bps → Gbps.",
              3: "Exactly size, %.2f, unit, and a newline — nothing else. Byte-identical to ex1.",
            },
          },
          diagram: "output-line",
          explain: [
            "The whole benchmark reduces to 21 lines: size, throughput in auto-scaled units, and nothing else — no debug prints, no timing internals. The output contract that verify.sh checks.",
            "Each line is one point on the envelope: this is the 'follow the data' spine's destination — every stop upstream exists to explain how these 21 numbers came out the way they did.",
          ],
        },
      ],
    },

    handshake: {
      id: "handshake",
      title: "The handshake",
      subtitle: "The one-time TCP exchange of QP addresses — and the control receive pool that is already armed",
      group: "Setup",
      adrs: ["0001"],
      concept: [
        "Before a single WRITE can be posted, each side must know where the other's QP lives: the LID (which port on the fabric), the QPN (which QP on that port), the PSN (where the packet stream starts) and the GID (the 128-bit global address, needed only on some fabrics) — plus, from the server, the buffer address and rkey the client's WRITEs will land in.",
        "The handshake is one TCP connection, once per run, before any data flows: each side sends its address as a fixed-size text line, the server also sends its buffer addr and rkey, and a final 'ready' beat keeps the socket open until both sides have what they need. After that, TCP is never used again — everything else rides the QP (ADR-0001).",
        "The handshake also connects the QPs: a QP must pass through its states (INIT → RTR → RTS) with the peer's address in hand. The server connects during the exchange — it has the client's address by then — and the client connects right after.",
        "And already armed: before the exchange, both sides posted the 32-deep control receive pool, so the moment the QPs connect, control messages can flow. Nothing can ever find the receive queue empty.",
      ],
      terms: [
        { term: "Handshake", def: "the one-time TCP exchange of QP addresses (LID/QPN/PSN/GID) and the server's buffer addr/rkey before any data flows" },
        { term: "Control receive pool", def: "the 32 receive WRs each side posts once at init to absorb all 21 per-direction control messages; never refreshed" },
        { term: "LID", def: "the port's 16-bit address on the fabric — what the HCA uses to route packets to the port" },
        { term: "QPN", def: "queue pair number — which QP on the remote port this QP talks to" },
        { term: "PSN", def: "packet sequence number — where the peer's packet stream starts; random, 24-bit" },
        { term: "rkey", def: "the key that lets the client's HCA write into the server's registered buffer" },
      ],
      code: {
        heading: "bw_exch_dest_client — one side of the exchange",
        file: "bw.c:349–424",
        lines: [
          "static struct bw_dest *bw_exch_dest_client(const char *servername, int port,",
          "                                           const struct bw_dest *my_dest)",
          "{",
          "    ...resolve the name; try each address until connect succeeds...",
          "",
          "    if (sockfd < 0) {",
          "        /* No server listening: fail silently — exit non-zero with nothing",
          "           printed (T1 acceptance criterion). */",
          "        return NULL;",
          "    }",
          "",
          "    gid_to_wire_gid(&my_dest->gid, gid);",
          "    memset(msg, 0, sizeof msg);",
          "    sprintf(msg, DEST_FMT, my_dest->lid, my_dest->qpn, my_dest->psn, gid);",
          "    if (!bw_write_full(sockfd, msg, sizeof msg)) {",
          "        fprintf(stderr, \"Couldn't send local address\\n\");",
          "        goto out;",
          "    }",
          "",
          "    if (!bw_read_full(sockfd, msg, sizeof msg)) {",
          "        perror(\"client read\");",
          "        fprintf(stderr, \"Couldn't read remote address\\n\");",
          "        goto out;",
          "    }",
          "",
          "    /* The server keeps the socket open until we signal receipt, so this",
          "     * must go out before we close. */",
          "    if (!bw_write_full(sockfd, \"ready\", sizeof \"ready\")) {",
          "        perror(\"client write\");",
          "        goto out;",
          "    }",
          "",
          "    rem_dest = bw_parse_dest(msg, 1);",
          "    if (!rem_dest) {",
          "        fprintf(stderr, \"Couldn't parse remote address\\n\");",
          "        goto out;",
          "    }",
          "",
          "out:",
          "    close(sockfd);",
          "    return rem_dest;",
          "}",
        ],
        annotations: {
          1: "The client side of the exchange: connect to the server's port, send my QP address, read the server's (with its buffer addr/rkey), signal 'ready'.",
          4: "getaddrinfo resolves the name — the assignment accepts a hostname or an IP — and the loop tries each resolved address until one connects.",
          6: "No server listening: exit non-zero with NOTHING printed — the T1 acceptance criterion verify.sh checks.",
          12: "My address first: the GID is serialized to its 32-hex-char wire form, the other fields are plain hex.",
          14: "One fixed 128-byte line: lid, qpn, psn, gid — DEST_FMT.",
          20: "Then the server's line — six fields: mine plus its buffer addr and rkey. The client's WRITEs will land there.",
          28: "'ready': the server holds the socket open until this beat, so it must go out before the client closes — else the server's read would truncate.",
          34: "Parse with expect_addr = 1: the server's addr/rkey are REQUIRED. A truncated server message must not pass with zeros.",
        },
      },
      why: [
        {
          adr: "ADR-0001",
          title: "Why TCP exists at all",
          text: "One exchange, once: TCP is only the handshake — addresses, before any data flows. Every message after that — data and control — rides the QP, because the control messages must be ordered against the WRITEs: an ack over TCP would not be, and the clock could stop early.",
        },
        {
          adr: "ADR-0001",
          title: "Why the pool is posted before the handshake",
          text: "The moment the QPs connect, control messages can arrive; an empty receive queue means a SEND that cannot complete. Posting the whole 32-deep control receive pool at init, before the exchange, makes the RQ always ready — and 32 > 21 covers a whole sweep with 11 spare, never refreshed.",
        },
        {
          adr: "audit",
          title: "Why the robust socket IO",
          text: "TCP is a byte stream: read() can return a short chunk, and the template read once and hoped. bw_read_full and bw_write_full loop until the fixed-size message is fully moved, and the 'ready' beat's read is checked — the audit's two robustness fixes over the template.",
        },
        {
          adr: "audit",
          title: "Why a random PSN",
          text: "The PSN starts at a fresh random 24-bit position every run (lrand48 & 0xffffff), so no two runs begin their packet streams the same way. The sweep's ~2.86M WRs never approach the 2^24 space, and RC PSN arithmetic is modular anyway (audit finding 4).",
        },
      ],
      whatifs: [
        {
          q: "What if the handshake messages were variable-length?",
          a: "The parse and the read loop both rely on the fixed 128-byte size: bw_read_full needs a length, and sscanf expects the exact field layout. Variable-length would need framing — finding where each message ends — which the template's fixed-size design deliberately avoids.",
        },
        {
          q: "What if both sides tried to connect their QPs before the exchange finished?",
          a: "A QP can only go RTR with the peer's address in hand, and only the exchange supplies it. The server connects mid-exchange (it has the client's address by then); the client connects after. The ordering is structural — neither side can move early, because the address is not there yet.",
        },
        {
          q: "What if the client closed the socket right after sending its address?",
          a: "The server's message would never arrive: the client's read would hit a closed stream and the run would die. The 'ready' beat is the fix — the client signals receipt, and only then closes; the server checks that beat's count (the template left it unchecked).",
        },
        {
          q: "What if a control message arrived with no receive posted?",
          a: "The SEND would be retried (RNR) and eventually error out — or worse, sit uncompleted while the sender's clock keeps waiting. The 32-deep pool, posted before the handshake, makes the case impossible by construction (ADR-0001).",
        },
      ],

      frames: [
        {
          id: "overview", title: "The handshake at a glance",
          diagram: "handshake-seq",
          explain: [
            "Everything that needs to be said is said once: the client sends its QP address, the server sends its address plus the buffer addr and rkey, the client says 'ready'. Then the socket closes forever — the QP is the only link from here on.",
            "The order matters: the server cannot send its own message before the client's address arrives, and the client must not close before the server has read its message — the 'ready' beat makes both safe.",
          ],
        },
        {
          id: "dest", title: "The address each side sends",
          code: {
            file: "bw.c:202–211, 1262–1287",
            lines: [
              "struct bw_dest {",
              "    int lid;",
              "    int qpn;",
              "    int psn;",
              "    union ibv_gid gid;",
              "    /* Server side only: buffer address and rkey for the client's RDMA",
              "     * WRITEs. Zero on the client (the server never touches client memory). */",
              "    uint64_t buf_addr;",
              "    uint32_t rkey;",
              "};",
              "",
              "    my_dest.lid = ctx->portinfo.lid;",
              "    ...",
              "    my_dest.qpn = ctx->qp->qp_num;",
              "    my_dest.psn = lrand48() & 0xffffff;",
              "",
              "    if (servername)",
              "        rem_dest = bw_exch_dest_client(servername, port, &my_dest);",
              "    else {",
              "        /* The server advertises its buffer — the client's RDMA WRITEs land",
              "         * here — and nothing else beyond the template's QP address. */",
              "        my_dest.buf_addr = (uint64_t) ctx->buf;",
              "        my_dest.rkey = ctx->mr->rkey;",
              "    }",
            ],
            annotations: {
              1: "struct bw_dest — one side's half of the handshake, as C values. It IS the message's parsed form (frame below).",
              2: "lid: the port's 16-bit address on the fabric — read from the port info.",
              4: "psn: a fresh random 24-bit start every run — a new packet stream position each time (audit).",
              5: "gid: the 128-bit global address; all zeros on the course fabric, which routes by LID.",
              8: "buf_addr + rkey: server only. The client's WRITEs land here; on the client these stay zero — the server never touches client memory.",
              12: "lid comes from the port info, read back from the device.",
              14: "qpn comes from the CREATED QP — the hardware assigned it.",
              15: "psn is random — lrand48 & 0xffffff, template-identical.",
              22: "The server fills the two fields the client needs: where to write, and the key that proves it may.",
            },
          },
          diagram: "dest-anatomy",
          explain: [
            "The handshake message is just these values rendered as text. Three come from the device (lid, qpn, gid), one is random (psn), and two are filled only by the server (buf_addr, rkey — the address of its 1 MB buffer and the key that lets the client's HCA write into it).",
            "Why text at all? It is one exchange, once per run — readability and a fixed sscanf layout beat a binary protocol's edge cases here.",
          ],
        },
        {
          id: "pool", title: "The control receive pool",
          code: {
            file: "bw.c:685–709",
            lines: [
              "static int bw_post_control_recvs(struct bw_context *ctx)",
              "{",
              "    struct ibv_sge list = {",
              "            .addr	= (uint64_t) ctx->ctrl_buf,",
              "            .length = CTRL_MSG_LEN,",
              "            .lkey	= ctx->ctrl_mr->lkey",
              "    };",
              "    struct ibv_recv_wr wr = {",
              "            .wr_id	    = BW_RECV_WRID,",
              "            .sg_list    = &list,",
              "            .num_sge    = 1,",
              "            .next       = NULL",
              "    };",
              "    struct ibv_recv_wr *bad_wr;",
              "    int i;",
              "",
              "    for (i = 0; i < CTRL_POOL_DEPTH; ++i)",
              "        if (ibv_post_recv(ctx->qp, &wr, &bad_wr))",
              "            break;",
              "",
              "    return i == CTRL_POOL_DEPTH ? 0 : 1;",
              "}",
            ],
            annotations: {
              1: "The whole pool, posted once right after init and BEFORE the handshake — no control message can ever find the RQ empty (ADR-0001).",
              4: "All 32 receives point at the SAME 64-byte control area — safe because at most one control message is ever in flight per direction (audit).",
              9: "All 32 share one wr_id (BW_RECV_WRID): which receive completed never matters — the poll loop only counts the wr_id.",
              17: "32 posts, one per loop pass.",
              21: "All 32 posted? Ready. A partial pool would leave a size's message with no receive to land in — the run fails here, not mid-sweep.",
            },
          },
          diagram: "rq-pool",
          explain: [
            "Every control message must find a posted receive, or the HCA cannot complete the peer's SEND. The pool is the fix: 32 receives posted once at init, before the handshake, all aimed at one 64-byte control area.",
            "Why 32? The run has exactly 21 dones (server side) and 21 acks (client side) — 21 of the 32 are used, 11 stay spare. Never refreshed, because the pool is sized to the whole run: a fixed supply for a fixed demand.",
          ],
        },
        {
          id: "io", title: "Robust socket IO",
          code: {
            file: "bw.c:236–260",
            lines: [
              "/* Loop until len bytes move or the stream ends: the handshake messages are",
              " * fixed-size, and a short read would break the parse. */",
              "static int bw_read_full(int fd, void *buf, size_t len)",
              "{",
              "    size_t got = 0;",
              "",
              "    while (got < len) {",
              "        ssize_t n = read(fd, (char *) buf + got, len - got);",
              "        if (n <= 0)",
              "            return 0;",
              "        got += n;",
              "    }",
              "    return 1;",
              "}",
              "",
              "static int bw_write_full(int fd, const void *buf, size_t len)",
              "{",
              "    size_t sent = 0;",
              "",
              "    while (sent < len) {",
              "        ssize_t n = write(fd, (const char *) buf + sent, len - sent);",
              "        if (n <= 0)",
              "            return 0;",
              "        sent += n;",
              "    }",
              "    return 1;",
              "}",
            ],
            annotations: {
              1: "TCP is a byte stream with no message boundaries: read() may return HALF a message, or more than one. The handshake messages are fixed-size, so the loop knows exactly how many bytes to demand.",
              7: "Keep reading until all len bytes are in — or the stream ends (n <= 0: the peer died).",
              8: "got tracks the accumulation; each read resumes where the last stopped.",
              16: "The write side gets the same discipline — a write can also go short.",
              20: "The template called read/write once and ignored the count; these loops are the audit's robustness fix — the parse below can trust the message.",
            },
          },
          diagram: "full-io",
          explain: [
            "TCP is a byte stream: read() may return half a message, or a message and a bit. The template read once and hoped; bw_read_full loops until all len bytes are in, so the parse can trust the message.",
            "The same for writing — and the 'ready' beat's read is checked too, where the template left it unchecked (audit).",
          ],
        },
        {
          id: "parse", title: "Parsing it back",
          code: {
            file: "bw.c:213–232, 262–285",
            lines: [
              "void wire_gid_to_gid(const char *wgid, union ibv_gid *gid)",
              "{",
              "    char tmp[9];",
              "    uint32_t v32;",
              "    int i;",
              "",
              "    for (tmp[8] = 0, i = 0; i < 4; ++i) {",
              "        memcpy(tmp, wgid + i * 8, 8);",
              "        sscanf(tmp, \"%x\", &v32);",
              "        *(uint32_t *)(&gid->raw[i * 4]) = ntohl(v32);",
              "    }",
              "}",
              "",
              "void gid_to_wire_gid(const union ibv_gid *gid, char wgid[])",
              "{",
              "    for (i = 0; i < 4; ++i)",
              "        sprintf(&wgid[i * 8], \"%08x\", htonl(*(uint32_t *)(gid->raw + i * 4)));",
              "}",
              "",
              "static struct bw_dest *bw_parse_dest(const char *msg, int expect_addr)",
              "{",
              "    struct bw_dest *dest = calloc(1, sizeof *dest);",
              "    char gid[33];",
              "    int n;",
              "",
              "    if (!dest)",
              "        return NULL;",
              "",
              "    n = sscanf(msg, DEST_FMT_PARSE,",
              "               &dest->lid, &dest->qpn, &dest->psn, gid,",
              "               &dest->buf_addr, &dest->rkey);",
              "    if (n < 4 || (expect_addr && n < 6)) {",
              "        free(dest);",
              "        return NULL;",
              "    }",
              "",
              "    wire_gid_to_gid(gid, &dest->gid);",
              "    return dest;",
              "}",
            ],
            annotations: {
              1: "The GID is 128 bits — too big for a bare socket string. Its wire form: four uint32s, 8 hex chars each, 32 chars total.",
              7: "wire_gid_to_gid: read each 8-hex-char chunk back into a uint32, ntohl to host byte order, store into the 16 raw bytes.",
              10: "ntohl / htonl are the honest part: the byte order of the wire is made explicit, never assumed.",
              14: "gid_to_wire_gid is the mirror, used when sending: raw bytes → 32 hex chars.",
              20: "bw_parse_dest — the incoming 128-byte line becomes a struct bw_dest.",
              29: "sscanf against the fixed layout: lid, qpn, psn, the 32-char GID, then addr and rkey.",
              32: "The guard: four fields always; the client (expect_addr = 1) demands six — a truncated server message must not pass with addr/rkey zero.",
            },
          },
          diagram: "parse",
          explain: [
            "The message is text, so it comes back with sscanf: lid, qpn, psn, the 32-hex-char GID, and — on the client — the server's addr and rkey. Four fields always; six when the client demands the buffer keys.",
            "The GID, being 128 bits, travels as 32 hex characters and is rebuilt into raw bytes with the byte order made explicit (htonl / ntohl).",
          ],
        },
        {
          id: "server-side", title: "The server's side — and the ready beat",
          code: {
            file: "bw_exch_dest_server · bw.c:426–536",
            lines: [
              "    listen(sockfd, 1);",
              "    connfd = accept(sockfd, NULL, 0);",
              "    close(sockfd);",
              "",
              "    if (!bw_read_full(connfd, msg, sizeof msg)) {",
              "        perror(\"server read\");",
              "        fprintf(stderr, \"Couldn't read remote address\\n\");",
              "        goto out;",
              "    }",
              "",
              "    rem_dest = bw_parse_dest(msg, 0);",
              "    if (!rem_dest) {",
              "        fprintf(stderr, \"Couldn't parse remote address\\n\");",
              "        goto out;",
              "    }",
              "",
              "    if (bw_connect_qp(ctx, ib_port, my_dest->psn, mtu, rem_dest, sgid_idx)) {",
              "        fprintf(stderr, \"Couldn't connect to remote QP\\n\");",
              "        ...free(rem_dest) and bail...",
              "    }",
              "",
              "    /* Send our address plus the buffer addr/rkey the client needs for its",
              "     * RDMA WRITEs. */",
              "    gid_to_wire_gid(&my_dest->gid, gid);",
              "    memset(msg, 0, sizeof msg);",
              "    sprintf(msg, DEST_FMT_SERVER,",
              "            my_dest->lid, my_dest->qpn, my_dest->psn, gid,",
              "            my_dest->buf_addr, my_dest->rkey);",
              "    if (!bw_write_full(connfd, msg, sizeof msg)) {",
              "        ...free(rem_dest) and bail...",
              "    }",
              "",
              "    /* Final beat: the client signals it has our address with \"ready\" and",
              "     * closes. The template leaves this read unchecked; the message is",
              "     * short, so check the count, not the message size. */",
              "    {",
              "        char ready[sizeof \"ready\"];",
              "",
              "        if (!bw_read_full(connfd, ready, sizeof ready)) {",
              "            perror(\"server read\");",
              "            ...free(rem_dest) and bail...",
              "        }",
              "    }",
            ],
            annotations: {
              1: "listen + accept: the server waits for the client's connection — one run, one socket, then the listen socket is closed.",
              5: "The server reads the client's address FIRST — it cannot send its own until the client's has arrived.",
              11: "expect_addr = 0: the client's four fields suffice — addr/rkey are the server's to give, not to receive.",
              17: "The server connects the QPs mid-exchange: it has the client's address NOW, so its QP walks RTR → RTS immediately. The client connects after the exchange, in main.",
              23: "Then the six-field message back: the client's four fields plus the buffer address and rkey its WRITEs need.",
              33: "The 'ready' beat: the server waits for the client to signal receipt before closing. The template left this read unchecked; here the count is checked — a dead client is an error, not a silent close.",
            },
          },
          diagram: "handshake-seq",
          explain: [
            "The server's side is the mirror, with one extra act: it connects the QPs in the middle of the exchange. It has the client's address after the first read — so its QP can go RTR → RTS before the exchange even ends. The client connects only after it has the server's address.",
            "Then the 'ready' beat: the client signals receipt, the server checks it (unlike the template), and the socket closes for good.",
          ],
        },
        {
          id: "qp-connect", title: "Connecting the QPs — RTR, then RTS",
          code: {
            file: "bw.c:287–347",
            lines: [
              "static int bw_connect_qp(struct bw_context *ctx, int port, int my_psn,",
              "                         enum ibv_mtu mtu,",
              "                         struct bw_dest *dest, int sgid_idx)",
              "{",
              "    struct ibv_qp_attr attr = {",
              "            .qp_state		= IBV_QPS_RTR,",
              "            .path_mtu		= mtu,",
              "            .dest_qp_num		= dest->qpn,",
              "            .rq_psn			= dest->psn,",
              "            .max_dest_rd_atomic	= 1,",
              "            .min_rnr_timer		= 12,",
              "            .ah_attr		= {",
              "                    .is_global	= 0,",
              "                    .dlid		= dest->lid,",
              "                    ...",
              "            }",
              "    };",
              "",
              "    /* GRH addressing is used iff the remote advertised a nonzero GID and we",
              "     * have a GID index of our own; a remote GID with no local index (-g on",
              "     * one side only) therefore degrades to LID-based addressing — the course",
              "     * fabric's normal mode — instead of failing RTR on sgid_index = -1. */",
              "    if (dest->gid.global.interface_id && sgid_idx >= 0) {",
              "        attr.ah_attr.is_global = 1;",
              "        attr.ah_attr.grh.hop_limit = 1;",
              "        attr.ah_attr.grh.dgid = dest->gid;",
              "        attr.ah_attr.grh.sgid_index = sgid_idx;",
              "    }",
              "    if (ibv_modify_qp(ctx->qp, &attr,",
              "            IBV_QP_STATE              |",
              "            IBV_QP_AV                 |",
              "            IBV_QP_PATH_MTU           |",
              "            IBV_QP_DEST_QPN           |",
              "            IBV_QP_RQ_PSN             |",
              "            IBV_QP_MAX_DEST_RD_ATOMIC |",
              "            IBV_QP_MIN_RNR_TIMER)) {",
              "        fprintf(stderr, \"Failed to modify QP to RTR\\n\");",
              "        return 1;",
              "    }",
              "",
              "    attr.qp_state	    = IBV_QPS_RTS;",
              "    attr.timeout	    = 14;",
              "    attr.retry_cnt	    = 7;",
              "    attr.rnr_retry	    = 7;",
              "    attr.sq_psn	    = my_psn;",
              "    attr.max_rd_atomic  = 1;",
              "    if (ibv_modify_qp(ctx->qp, &attr,",
              "            IBV_QP_STATE              |",
              "            IBV_QP_TIMEOUT            |",
              "            IBV_QP_RETRY_CNT          |",
              "            IBV_QP_RNR_RETRY          |",
              "            IBV_QP_SQ_PSN             |",
              "            IBV_QP_MAX_QP_RD_ATOMIC)) {",
              "        fprintf(stderr, \"Failed to modify QP to RTS\\n\");",
              "        return 1;",
              "    }",
              "",
              "    return 0;",
              "}",
            ],
            annotations: {
              1: "The QP's last two state changes — with the peer's address in hand, RTR then RTS.",
              6: "RTR (ready to receive): the QP learns about the PEER — its QPN, its PSN, the path MTU.",
              11: "min_rnr_timer 12: how long to back off when the peer's receive queue is momentarily full (RNR) before retrying.",
              14: "The address handle: which local port and which remote LID to route to.",
              19: "GRH only when actually needed: the remote advertised a nonzero GID AND we have a local GID index (-g). One-sided -g degrades to LID mode — the course fabric's normal mode — instead of failing RTR (audit).",
              29: "The RTR modify: state + address + MTU + peer QPN/PSN together.",
              38: "RTS (ready to send): the QP can now transmit.",
              39: "timeout 14 / retry 7 / rnr_retry 7 — the RC reliability parameters: how long and how hard to retry before the HCA reports an error.",
              42: "sq_psn = MY psn: where MY packet stream starts — the value the peer read from my handshake message.",
            },
          },
          diagram: "qp-states",
          explain: [
            "A QP is born in RESET and must be walked through its states: INIT (created and pointed at a port — the memory-region stop), RTR (ready to receive — it now knows the peer), RTS (ready to send — the peer knows it).",
            "The handshake supplies the address at exactly the right moment: the server walks RTR → RTS during the exchange, the client right after. Only then can WRITEs flow.",
          ],
        },
      ],
    },

    "memory-region": {
      id: "memory-region",
      title: "Memory region",
      subtitle: "The registered 1 MB buffer, the keys that gate it, and the QP init builds",
      group: "Setup",
      adrs: ["0002"],
      concept: [
        "The data path needs memory the HCA can touch. A plain malloc'd buffer is invisible to the hardware: DMA requires registration — ibv_reg_mr pins the pages and hands back the two keys that make RDMA legal: lkey for the local HCA to read the buffer, rkey for a remote HCA to write it.",
        "Each side registers one 1 MB buffer, page-aligned, filled with a distinctive byte pattern, and never modified again. The server's registration adds REMOTE_WRITE — the client's WRITEs land there. The client's is local-only: its own HCA reads it.",
        "Init (bw_init_ctx) builds everything else the run needs: a small second registration for the control area, one shared CQ for completions, and the QP itself — created with the window + slack depth and the inline declaration, stepped down until mlx4 accepts it, read back via ibv_query_qp: 'we asked the hardware, not a header'.",
      ],
      terms: [
        { term: "PD", def: "protection domain — the container tying the QP and its memory regions together; a QP can only use MRs in its own PD" },
        { term: "MR", def: "memory region — pinned memory with the keys that permit access; registered once at init" },
        { term: "lkey", def: "the local key — lets this QP's HCA read the buffer" },
        { term: "rkey", def: "the remote key — lets the peer's HCA write the buffer (server only); without REMOTE_WRITE the WRITE fails" },
        { term: "CQ", def: "completion queue — where the HCA posts completions; one shared CQ for send and receive completions" },
        { term: "sq_depth", def: "the QP's negotiated send depth — what ibv_query_qp reports back, not what was requested" },
      ],
      code: {
        heading: "bw_init_ctx — QP create: declare, step down, read back",
        file: "bw.c:538–683",
        lines: [
          "    {",
          "        int try_inline;",
          "",
          "        /* The inline declaration is stepped down until QP creation",
          "         * succeeds: mlx4 rejects the QP when the declared max_inline_data",
          "         * (plus WQE overhead) exceeds what the hardware accepts, and no",
          "         * portable query exposes that ceiling on every stack. The value",
          "         * the QP was actually created with is read back below; that",
          "         * read-back is the runtime max_inline_data the data path uses. */",
          "        for (try_inline = MAX_INLINE_DATA_DECLARE;; try_inline -= 64) {",
          "            struct ibv_qp_init_attr attr = {",
          "                    .send_cq = ctx->cq,",
          "                    .recv_cq = ctx->cq,",
          "                    .cap     = {",
          "                            .max_send_wr  = max_send_wr,",
          "                            .max_recv_wr  = max_recv_wr,",
          "                            .max_send_sge = 1,",
          "                            .max_recv_sge = 1,",
          "                            .max_inline_data = try_inline",
          "                    },",
          "                    .qp_type = IBV_QPT_RC",
          "            };",
          "",
          "            ctx->qp = ibv_create_qp(ctx->pd, &attr);",
          "            if (ctx->qp || try_inline <= 0)",
          "                break;",
          "        }",
          "        if (!ctx->qp) {",
          "            fprintf(stderr,",
          "                    \"Couldn't create QP (send_wr %u, recv_wr %u, inline %d): %s\\n\",",
          "                    max_send_wr, max_recv_wr, try_inline, strerror(errno));",
          "            return NULL;",
          "        }",
          "    }",
          "",
          "    {",
          "        /* The runtime max_inline_data: read back what the QP was created",
          "         * with, since the driver may clamp the request. */",
          "        struct ibv_qp_attr attr;",
          "        struct ibv_qp_init_attr init_attr;",
          "",
          "        if (ibv_query_qp(ctx->qp, &attr, IBV_QP_CAP, &init_attr)) {",
          "            fprintf(stderr, \"Couldn't query QP attributes\\n\");",
          "            return NULL;",
          "        }",
          "        ctx->max_inline_data = init_attr.cap.max_inline_data;",
          "        ctx->sq_depth = init_attr.cap.max_send_wr;",
          "    }",
        ],
        annotations: {
          10: "Declare the largest inline we want — 1024 — and step down 64 B at a time until creation succeeds. Sixteen attempts; 0 is the floor (audit).",
          12: "One CQ serves both the SQ and the RQ: data, done, ack completions all land here, in order.",
          15: "The depths: max_send_wr = window + slack, max_recv_wr = 32 — both clamped to the device's max_qp_wr (previous frame).",
          19: "The declaration being stepped: the one knob mlx4 is picky about.",
          24: "One attempt per rung. Success — or hitting 0 — ends the loop; a final NULL is a clean error.",
          42: "The read-back: ibv_query_qp reports what the QP was ACTUALLY created with — the driver may have clamped our request.",
          46: "That read-back is the runtime max_inline_data the data path uses — 'we asked the hardware, not a header' (ADR-0002).",
          47: "sq_depth too: the refill's second condition (posting stop) paces the pipeline by this read-back depth.",
        },
      },
      why: [
        {
          adr: "ADR-0002",
          title: "Why one 1 MB buffer, never modified",
          text: "A window of 256 outstanding WRITEs means the buffer must stay valid until the last completion lands. One registered buffer, never written after init, removes the whole class of buffer-reuse bugs — no cycling, no re-registration, nothing to get wrong at full window depth.",
        },
        {
          adr: "ADR-0002",
          title: "Why declare-then-read-back",
          text: "No portable call says 'how much inline can this QP take?' — mlx4 just refuses QP creation when the declaration (plus WQE overhead) is too big. So the code declares 1024, steps down 64 at a time until creation succeeds, then reads back what was created via ibv_query_qp. That read-back is the runtime max_inline_data the data path uses — 'we asked the hardware, not a header'. It works identically on the course nodes' old OFED and the modern WSL build.",
        },
        {
          adr: "ADR-0002",
          title: "Why the slack above the window",
          text: "The SQ is created window + QP_SLACK deep, so the last K-WR list's overshoot of the window and the per-size done SEND both always fit — the done can never find the SQ full. k ≤ QP_SLACK keeps the refill's guarantee, and the max_qp_wr clamp keeps it honest on smaller hardware (audit's proved invariant).",
        },
        {
          adr: "ADR-0002",
          title: "Why REMOTE_WRITE only on the server",
          text: "Least privilege: the client's buffer is only ever read by its own HCA, so it needs no remote permission; the server's must accept the client's WRITEs. The rkey is the proof a WRITE presents — without REMOTE_WRITE that proof is not valid for remote writes, and the WRITE fails with a protection error.",
        },
      ],
      whatifs: [
        {
          q: "What if the buffer were not registered?",
          a: "The HCA can only DMA from registered, pinned memory. Without the MR there is no lkey for the SGE, and the post fails. Registration is the deal that makes the hardware trust the address — pin the pages, get the keys.",
        },
        {
          q: "What if the server forgot REMOTE_WRITE?",
          a: "The client's WRITEs would complete with a protection error: the server's rkey would not permit remote writes, and bw_wc_bad would abort the run. The flag is what makes the server's memory writable from the other side — the viva's simplest question.",
        },
        {
          q: "What if the buffer were modified while WRITEs were outstanding?",
          a: "A WRITE in flight reads the payload when it reaches it, so a modified buffer means some WRITEs carry new data and some old — nondeterministic results. With 256 outstanding, the last posted may complete after the buffer changed. The design's answer: never modify after init — the hazard removed by construction (ADR-0002).",
        },
        {
          q: "What if max_inline_data were declared but never read back?",
          a: "The data path would believe 1024 even if the driver clamped lower — but a QP clamped below the declaration is exactly what mlx4 refused to create, so the run would not exist. The read-back is what makes the declaration safe: we discover the truth, then use it.",
        },
      ],

      frames: [
        {
          id: "buffer", title: "One buffer, registered once",
          code: {
            file: "bw.c:550–556, 592–605",
            lines: [
              "    ctx->buf = malloc(roundup(BUFFER_SIZE, page_size));",
              "    if (!ctx->buf) {",
              "        fprintf(stderr, \"Couldn't allocate work buf.\\n\");",
              "        return NULL;",
              "    }",
              "",
              "    memset(ctx->buf, 0x7b + is_server, BUFFER_SIZE);",
              "",
              "    ctx->mr = ibv_reg_mr(ctx->pd, ctx->buf, BUFFER_SIZE,",
              "                         IBV_ACCESS_LOCAL_WRITE |",
              "                         (is_server ? IBV_ACCESS_REMOTE_WRITE : 0));",
              "    if (!ctx->mr) {",
              "        fprintf(stderr, \"Couldn't register MR\\n\");",
              "        return NULL;",
              "    }",
              "",
              "    ctx->ctrl_mr = ibv_reg_mr(ctx->pd, ctx->ctrl_buf, CTRL_MSG_LEN,",
              "                              IBV_ACCESS_LOCAL_WRITE);",
            ],
            annotations: {
              1: "1 MB, rounded up to a page boundary — registration works on whole pages; the alignment keeps the entire buffer mappable.",
              7: "The fill: 0x7b ('{') on the client, 0x7c ('|') on the server — two identical buffers you can tell apart, and a visible pattern for debugging what landed where.",
              9: "Registration — the deal with the HCA: pin the pages, get the keys. LOCAL_WRITE always; REMOTE_WRITE only on the server, whose buffer is where the client's WRITEs land.",
              11: "The server's rkey is what the client's WRITEs present; without REMOTE_WRITE that rkey is not valid for remote writes and the WRITE fails with a protection error.",
              17: "A second, tiny registration for the control area — the 64 bytes the control messages land in.",
            },
          },
          diagram: "registration",
          explain: [
            "RDMA does not touch ordinary malloc'd memory: the HCA may only DMA from registered, pinned pages. ibv_reg_mr makes the deal — pages pinned, keys issued that prove permission.",
            "One buffer, registered once, never modified after init. With 256 WRITEs outstanding, the last posted must still find its payload valid when its completion lands — a never-touched buffer removes the reuse hazard by construction (ADR-0002).",
          ],
        },
        {
          id: "cq", title: "The CQ — completions land here",
          code: {
            file: "bw.c:607–612",
            lines: [
              "    ctx->cq = ibv_create_cq(ctx->context, max_send_wr + max_recv_wr,",
              "                            NULL, NULL, 0);",
              "    if (!ctx->cq) {",
              "        fprintf(stderr, \"Couldn't create CQ\\n\");",
              "        return NULL;",
              "    }",
            ],
            annotations: {
              1: "One CQ serves both the SQ and the RQ — send completions and receive completions merge into one ordered queue.",
              2: "Depth = max_send_wr + max_recv_wr, the true worst case: a full SQ's completions plus the 32 receives. The CQ can never overflow (audit).",
              5: "Every poll loop in the program — the refill, the done/ack waits — reads this one queue.",
            },
          },
          diagram: "cq-shared",
          explain: [
            "Every completion — a data WRITE finished, the done-send sent, the ack received — lands in this one queue. That is what makes the wr_id taxonomy work: the poll loops read a single queue and route each completion by its wr_id.",
            "The depth is the worst case on purpose, so no completion is ever dropped for lack of room: sq_depth signaled sends plus 32 receives.",
          ],
        },
        {
          id: "create", title: "QP create — asking the hardware",
          code: {
            file: "bw.c:614–661",
            lines: [
              "    {",
              "        int try_inline;",
              "",
              "        /* The inline declaration is stepped down until QP creation",
              "         * succeeds: mlx4 rejects the QP when the declared max_inline_data",
              "         * (plus WQE overhead) exceeds what the hardware accepts, and no",
              "         * portable query exposes that ceiling on every stack. */",
              "        for (try_inline = MAX_INLINE_DATA_DECLARE;; try_inline -= 64) {",
              "            struct ibv_qp_init_attr attr = {",
              "                    .send_cq = ctx->cq,",
              "                    .recv_cq = ctx->cq,",
              "                    .cap     = {",
              "                            .max_send_wr  = max_send_wr,",
              "                            .max_recv_wr  = max_recv_wr,",
              "                            .max_inline_data = try_inline",
              "                    },",
              "                    .qp_type = IBV_QPT_RC",
              "            };",
              "",
              "            ctx->qp = ibv_create_qp(ctx->pd, &attr);",
              "            if (ctx->qp || try_inline <= 0)",
              "                break;",
              "        }",
              "        if (!ctx->qp) {",
              "            ...clean error...",
              "        }",
              "    }",
              "",
              "    {",
              "        struct ibv_qp_attr attr;",
              "        struct ibv_qp_init_attr init_attr;",
              "",
              "        if (ibv_query_qp(ctx->qp, &attr, IBV_QP_CAP, &init_attr)) {",
              "            fprintf(stderr, \"Couldn't query QP attributes\\n\");",
              "            return NULL;",
              "        }",
              "        ctx->max_inline_data = init_attr.cap.max_inline_data;",
              "        ctx->sq_depth = init_attr.cap.max_send_wr;",
              "    }",
            ],
            annotations: {
              8: "Declare the largest inline we want — 1024 — and step down 64 B at a time until creation succeeds. Sixteen attempts; 0 is the floor (audit).",
              13: "The depths: window + slack sends, 32 receives — both clamped to the device's max_qp_wr (next frame).",
              16: "The declaration being stepped: the one knob mlx4 is picky about.",
              20: "One attempt per rung. Success — or hitting 0 — ends the loop; a final NULL is a clean error.",
              32: "The read-back: ibv_query_qp reports what the QP was ACTUALLY created with — the driver may have clamped our request.",
              35: "That read-back is the runtime max_inline_data the data path uses — 'we asked the hardware, not a header' (ADR-0002).",
              36: "sq_depth too: the refill's second condition (posting stop) paces the pipeline by this read-back depth.",
            },
          },
          diagram: "inline-stepping",
          explain: [
            "The QP's inline capacity is a hardware fact, and it is not portable to ask about: mlx4 simply rejects a QP whose declared max_inline_data (plus WQE overhead) is too big. So the code declares the largest value it wants and steps down 64 B at a time until creation succeeds.",
            "Then the read-back: ibv_query_qp reports what the QP was actually created with. That number — not the declared one — is the runtime max_inline_data the data path uses. 'We asked the hardware, not a header.'",
          ],
          whatif: {
            q: "What if the declared value were used as-is, without the read-back?",
            a: "The data path would inline up to 1024 B even when the driver clamped lower — and a QP clamped below the declaration is exactly what mlx4 refused, so the run would fail at init. Declare-then-read-back turns a guess into a discovery, and it works identically on the course nodes' old OFED and the modern WSL build (ADR-0002).",
          },
        },
        {
          id: "depth", title: "The cap block — how deep the SQ is",
          code: {
            file: "bw.c:571–582",
            lines: [
              "    if (ibv_query_device(ctx->context, &dev_attr)) {",
              "        fprintf(stderr, \"Couldn't query device attributes\\n\");",
              "        return NULL;",
              "    }",
              "    max_send_wr = window + QP_SLACK;",
              "    max_recv_wr = CTRL_POOL_DEPTH;",
              "    if (max_send_wr > (uint32_t) dev_attr.max_qp_wr)",
              "        max_send_wr = dev_attr.max_qp_wr;",
              "    if (max_recv_wr > (uint32_t) dev_attr.max_qp_wr)",
              "        max_recv_wr = dev_attr.max_qp_wr;",
            ],
            annotations: {
              1: "Ask the device for its per-QP WR limit (max_qp_wr) — the ceiling every depth is clamped to.",
              5: "The SQ depth: window + slack. The slack (1024) absorbs the last K-WR list's overshoot of the window AND the per-size done SEND — neither can find the SQ full (audit's proved invariant).",
              6: "The RQ depth: exactly the 32-deep control pool.",
              7: "The clamp: a device with a smaller max_qp_wr gets a shallower QP — and the refill's second condition (outstanding + k ≥ sq_depth) keeps the pipeline safe at any depth (audit).",
            },
          },
          diagram: "sq-depth",
          explain: [
            "The SQ is not exactly W deep: it is W + slack. The slack is the headroom the refill's discipline needs — the last list of a batch overshoots the window by up to K, and the per-size done SEND must never find the queue full.",
            "On the course hardware max_qp_wr ≥ 1536 (the T6 campaign requested 1536/1280/1536 and every QP was created), so the default request of 1280 is accepted un-clamped; the clamp exists for smaller devices, and the read-back sq_depth is what the refill actually paces by.",
          ],
        },
        {
          id: "init", title: "INIT — pointing the QP at the port",
          code: {
            file: "bw.c:663–680",
            lines: [
              "    {",
              "        struct ibv_qp_attr attr = {",
              "                .qp_state        = IBV_QPS_INIT,",
              "                .pkey_index      = 0,",
              "                .port_num        = port,",
              "                .qp_access_flags = IBV_ACCESS_REMOTE_READ |",
              "                IBV_ACCESS_REMOTE_WRITE",
              "        };",
              "",
              "        if (ibv_modify_qp(ctx->qp, &attr,",
              "                IBV_QP_STATE              |",
              "                IBV_QP_PKEY_INDEX         |",
              "                IBV_QP_PORT               |",
              "                IBV_QP_ACCESS_FLAGS)) {",
              "            fprintf(stderr, \"Failed to modify QP to INIT\\n\");",
              "            return NULL;",
              "        }",
              "    }",
            ],
            annotations: {
              3: "INIT: the QP's first state change after creation — it now belongs to a port on the fabric.",
              6: "qp_access_flags: what THIS QP allows OTHERS to do to it — the capability side of the rkey story. The server's rkey is the proof the client's WRITE presents; these flags are the permission behind it.",
              10: "RTR and RTS come later, in the handshake, when each side holds the peer's address.",
            },
          },
          diagram: "qp-states",
          explain: [
            "A QP is born in RESET and walks through its states in order: INIT (created and pointed at a port), RTR (ready to receive — knows the peer), RTS (ready to send — the peer knows it).",
            "This stop covers init: the QP is created and moved to INIT. The handshake stop covers RTR and RTS — they need the peer's address, which only the handshake can supply.",
          ],
        },
        {
          id: "ctx", title: "The state it all builds",
          code: {
            file: "bw.c:188–200",
            lines: [
              "struct bw_context {",
              "    struct ibv_context		*context;",
              "    struct ibv_pd		*pd;",
              "    struct ibv_mr		*mr;      /* the 1 MB buffer */",
              "    struct ibv_mr		*ctrl_mr; /* the control receive area */",
              "    struct ibv_cq		*cq;",
              "    struct ibv_qp		*qp;",
              "    void			*buf;     /* the 1 MB buffer */",
              "    void			*ctrl_buf;/* the control receive area */",
              "    uint32_t		 max_inline_data; /* the QP's negotiated max_inline_data */",
              "    uint32_t		 sq_depth;      /* the QP's negotiated max_send_wr */",
              "    struct ibv_port_attr	 portinfo;",
              "};",
            ],
            annotations: {
              1: "Everything init builds, in one struct: the device, the PD, both MRs, the CQ, the QP, the buffers.",
              4: "The two READ-BACK numbers — the ones the hardware negotiated at QP create, not the ones we asked for.",
              5: "portinfo: the port state queried right before the handshake — its LID and active MTU come from here.",
            },
          },
          diagram: "ctx-struct",
          explain: [
            "This is the setup, in one place: every resource the run uses, plus the two numbers the hardware negotiated at QP create. The handshake reads three things out of it (lid, qpn, mtu); the data path reads the rest.",
            "Teardown walks it in reverse — QP, CQ, MRs, PD, device — in the harness chapter of the closing stops.",
          ],
        },
      ],
    },

    posting: {
      id: "posting",
      title: "Posting the window",
      subtitle: "W = 256 outstanding, K = 64 signaled, the SQ never empties",
      group: "Data path",
      adrs: ["0002"],
      concept: [
        "The data path is a pipeline, not a loop that waits. The client keeps up to W = 256 WRITEs outstanding in the SQ — the window — and posts them in linked lists of K = 64 WRs per ibv_post_send call, so one doorbell covers 64 WRITEs instead of one per WRITE.",
        "Only every K-th WRITE is signaled (generates a CQE). Because RC completions are in-order, one CQE accounts for exactly K WRITEs — completions are counted in exact multiples of K, and 256/64 = 4 CQEs cover the whole window.",
        "The refill discipline sits between lists: while the window is full, poll the CQEs that are ready and reclaim their slots; then post the next list immediately. The SQ never drains to zero, so the NIC never idles. Messages ≤ max_inline_data ride the WQE inline (IBV_SEND_INLINE); larger ones are DMA-read from the single registered 1 MB buffer.",
      ],
      terms: [
        { term: "Window depth (W)", def: "how many outstanding WRs the SQ may hold; the pipeline never drains below it (default 256)" },
        { term: "Signal interval (K)", def: "every K-th WR generates a CQE; completions accounted in exact multiples of K (default 64)" },
        { term: "Refill", def: "reclaim only the CQEs that are ready, then immediately repost — the SQ never empties" },
        { term: "Inline", def: "message data rides inside the WQE at post time instead of being DMA-read from a buffer" },
        { term: "max_inline_data", def: "the device's inline limit, declared at QP creation and read back at runtime" },
      ],
      code: {
        heading: "bw_refill + bw_post_writes — the windowed stream",
        file: "bw.c:868–949",
        lines: [
          "/* bw_refill: reclaim ready CQEs while the window is full */",
          "while (st->outstanding >= window ||",
          "       st->outstanding + k >= (uint64_t) ctx->sq_depth) {",
          "    struct ibv_wc wc;",
          "    int ne = ibv_poll_cq(ctx->cq, 1, &wc);",
          "    if (ne == 0) continue;",
          "    if (bw_wc_bad(&wc, 1ull << BW_DATA_WRID)) return 1;",
          "    st->outstanding -= k;",
          "}",
          "",
          "/* bw_post_writes: post n WRITEs as K-WR linked lists */",
          "while (n > 0) {",
          "    uint64_t chunk = n < k ? n : k;",
          "    if (bw_refill(ctx, window, k, st)) return 1;",
          "    for (i = 0; i < chunk; ++i) {",
          "        uint64_t t = st->posted + i + 1;",
          "        uint32_t signal = (t % k == 0) ||",
          "                         (final && n == chunk && i == chunk - 1);",
          "        sges[i] = (struct ibv_sge) {",
          "            .addr = (uint64_t) ctx->buf, .length = size,",
          "            .lkey = ctx->mr->lkey };",
          "        wrs[i] = (struct ibv_send_wr) {",
          "            .wr_id = BW_DATA_WRID, .opcode = IBV_WR_RDMA_WRITE,",
          "            .send_flags = inline_flag | (signal ? IBV_SEND_SIGNALED : 0),",
          "            .sg_list = &sges[i], .num_sge = 1,",
          "            .next = i + 1 < chunk ? &wrs[i + 1] : NULL };",
          "        wrs[i].wr.rdma.remote_addr = dest->buf_addr;",
          "        wrs[i].wr.rdma.rkey = dest->rkey;",
          "    }",
          "    if (ibv_post_send(ctx->qp, &wrs[0], &bad_wr)) return 1;",
          "    st->posted += chunk; st->outstanding += chunk; n -= chunk;",
          "}",
        ],
        annotations: {
          1: "The refill runs at the head of every list post — never in the middle of the pipe.",
          2: "Window full (outstanding ≥ W) OR the SQ's device-clamped depth is close: keep room for the next K-WR list.",
          4: "Poll ONE CQE at a time — no batch reaping. The loop retries when the CQ is momentarily empty (WRITEs still in flight).",
          6: "One data CQE = exactly K WRs. This is the whole trick: in-order RC completions make the accounting exact.",
          9: "Each pass posts one linked list of up to K WRs. The last list takes the remainder (n % k WRs).",
          10: "Refill first, post next: the SQ never drains to zero — the NIC never idles. The template's wait-for-all pattern was rejected here (ADR-0002).",
          12: "t = this WR's position in the whole size stream (warmup + timed).",
          13: "Signal schedule: the K-th WR of the stream, plus the stream's very last WR (the remainder) — the final CQE the ack wait consumes.",
          16: "All WRITEs reference the same registered 1 MB buffer, never modified after init — no buffer-reuse hazard at full window depth.",
          18: "IBV_WR_RDMA_WRITE: the HCA reads from this buffer and writes straight into the server's memory, no server CPU.",
          21: "The remote address and rkey from the handshake — the server gave them over TCP before any data flowed.",
          23: "One ibv_post_send call = one doorbell for K WRITEs. This is what beat the naive path's +37–67% at small sizes (ADR-0005).",
        },
      },
      why: [
        {
          adr: "ADR-0002",
          title: "Why the refill replaces the template's wait-for-all",
          text: "The template's pp_wait_completions posts a window, waits for ALL of it, then reposts. Every window, the SQ drains to zero and the NIC idles for roughly a round trip, then re-pays the ramp-up. The refill-never-empty discipline polls only the CQEs that are ready and reposts immediately — the SQ holds the window continuously, and the measured gain at ≤ 64 B was +37–67% in message rate. The user's viva line: 'we asked the hardware, not the header'.",
        },
        {
          adr: "ADR-0002",
          title: "Why K = 64 signals instead of every WRITE",
          text: "Fewer CQEs means less poll pressure in the refill — one CQE per K WRs instead of one per WRITE — and the accounting stays exact because RC completions are in-order: CQE #j covers WRs j·K−K+1…j·K, no bookkeeping needed. K is bounded by the window and by QP_SLACK so the done SEND always finds a free SQ slot.",
        },
        {
          adr: "ADR-0002",
          title: "Why one 1 MB buffer, never modified",
          text: "A window of 256 outstanding WRITEs means the last posted WRITE's buffer must still be valid when its completion lands. With a single registered buffer that is never written after init, there is no reuse hazard and no buffer cycling — the classic RDMA bug the design simply removes.",
        },
        {
          adr: "ADR-0002",
          title: "Why inline ≤ max_inline_data, declared then read back",
          text: "Small messages ride the WQE itself instead of being DMA-read — one less read from host memory per message. The limit is discovered the robust way: declare max_inline_data at QP creation (stepping down 1024 → 0 until mlx4 accepts) and read the created value back via ibv_query_qp — 'we asked the hardware, not a header'.",
        },
      ],
      whatifs: [
        {
          q: "What if we signaled every WRITE (K = 1)?",
          a: "Four times the CQE pressure in the refill, exact accounting retained. The T6 A/B measured it: (256,128) and (512,128) land within 0.1% of the default at every anchor size — the CQE rate is simply not a factor at these window depths. The naive T4 path, which posted one WRITE per doorbell and waited for all completions, was already bus-saturated at DMA sizes (ADR-0005).",
        },
        {
          q: "What if we used the template's wait-for-all pattern?",
          a: "Each window would drain to zero and idle for ~an RTT, then re-pay the ramp-up. That is exactly the T4 naive path, and the A/B measured the pipeline's win: +37–67% message rate at ≤ 64 B, identical elsewhere. The refill's gain is real and localized to the small sizes where message rate is the binding constraint.",
        },
        {
          q: "What if W were too small to cover the RTT × bandwidth product?",
          a: "The pipe could not stay full — the wire would go quiet every window. The T6 A/B pushed W to 512 and measured no change, and even the naive path saturated the bus, so 256 is deep enough on this hardware. The honest viva answer: W = 256 was the assumed default; the measurement campaign confirmed it is the optimum (ADR-0006/0007).",
        },
        {
          q: "What if max_inline_data were bigger (or we didn't declare it)?",
          a: "The inline path carries a per-message payload copy at ~853 MB/s (measured, ADR-0004), which caps messages ≤ max_inline_data at ~6.4–6.55 Gbps. A bigger limit would extend the copy plateau to bigger sizes; without the declaration, the stack still inlines small messages anyway — the measured envelope is identical with and without the flag. The boundary at 1 KB is exactly max_inline_data (research ticket #12).",
        },
      ],

      frames: [
        {
          id: "window", title: "The window — W = 256",
          code: {
            file: "bw.c:868–888",
            lines: [
              "while (st->outstanding >= window ||",
              "       st->outstanding + k >= (uint64_t) ctx->sq_depth) {",
              "    struct ibv_wc wc;",
              "    int ne = ibv_poll_cq(ctx->cq, 1, &wc);",
              "    if (ne == 0) continue;",
              "    if (bw_wc_bad(&wc, 1ull << BW_DATA_WRID)) return 1;",
              "    st->outstanding -= k;",
              "}",
            ],
            annotations: {
              1: "The window test: 256 WRITEs may be outstanding before the refill has to reclaim.",
              2: "Second condition: the device-clamped SQ depth — keep room for the next K-WR list.",
              4: "Poll ONE CQE at a time; retry while the CQ is momentarily empty (WRITEs still in flight).",
              7: "One data CQE = exactly K WRs (in-order RC) — the accounting is exact.",
            },
          },
          diagram: "sq-slots",
          explain: [
            "The SQ is a hardware ring that may hold up to W = 256 posted-but-uncompleted WRs. 'Outstanding' is the count the client tracks: posted minus reclaimed.",
            "The window exists because the wire is far away: it takes ~RTT for a WRITE to be acknowledged by a completion. With W = 256 deep, the client always has work queued — the HCA never runs dry.",
          ],
          why: {
            adr: "0002",
            title: "Why 256, measured not guessed",
            text: "W = 256 was the assumed default; the T6 A/B (ADR-0006/0007) pushed 512 and 128 and measured no change at any size — 256 is the measured optimum on this hardware.",
          },
        },
        {
          id: "signal", title: "K = 64 — the signal schedule",
          code: {
            file: "bw.c:912–921",
            lines: [
              "for (i = 0; i < chunk; ++i) {",
              "    uint64_t t = st->posted + i + 1;",
              "    uint32_t signal = (t % k == 0) ||",
              "                     (final && n == chunk && i == chunk - 1);",
              "    wrs[i] = (struct ibv_send_wr) {",
              "        .wr_id = BW_DATA_WRID, .opcode = IBV_WR_RDMA_WRITE,",
              "        .send_flags = inline_flag | (signal ? IBV_SEND_SIGNALED : 0),",
              "        ...",
            ],
            annotations: {
              1: "t = this WR's position in the whole size stream (warmup + timed).",
              3: "Signal schedule: every K-th WR of the stream …",
              4: "… plus the stream's very last WR — the remainder's CQE that the ack wait consumes.",
              7: "Only signaled WRs generate a CQE. The HCA processes every WR; the flag only controls the completion.",
            },
          },
          diagram: "signal-schedule",
          explain: [
            "Every K-th WRITE is signaled — 1 CQE per K WRs, so a full window of 256 costs just 4 CQEs. The HCA still does every WRITE; the flag only controls which ones generate completions.",
            "Why is the accounting exact? RC completions are in-order: CQE #j covers exactly WRs j·K−K+1 … j·K. No per-WR bookkeeping, no guessing.",
          ],
          why: {
            adr: "0002",
            title: "Why fewer CQEs help",
            text: "The refill polls the CQ; fewer CQEs means less time polling and more time posting. The measured small-size win over the naive path (+37–67%) is partly this: batching also removed one doorbell per WRITE.",
          },
        },
        {
          id: "list", title: "The linked list of WRs",
          code: {
            file: "bw.c:914–940",
            lines: [
              "for (i = 0; i < chunk; ++i) {",
              "    sges[i] = (struct ibv_sge) {",
              "        .addr = (uint64_t) ctx->buf, .length = size,",
              "        .lkey = ctx->mr->lkey };",
              "    wrs[i] = (struct ibv_send_wr) {",
              "        .wr_id = BW_DATA_WRID, .opcode = IBV_WR_RDMA_WRITE,",
              "        .send_flags = inline_flag | (signal ? IBV_SEND_SIGNALED : 0),",
              "        .sg_list = &sges[i], .num_sge = 1,",
              "        .next = i + 1 < chunk ? &wrs[i + 1] : NULL };",
              "    wrs[i].wr.rdma.remote_addr = dest->buf_addr;",
              "    wrs[i].wr.rdma.rkey = dest->rkey;",
              "}",
              "if (ibv_post_send(ctx->qp, &wrs[0], &bad_wr)) return 1;",
            ],
            annotations: {
              2: "One SGE per WR: this WR's data lives at ctx->buf (the 1 MB registered buffer), lkey proves the registration.",
              5: "The WR itself: opcode RDMA_WRITE, wr_id shared by all data WRITEs so completions stay distinguishable from control messages.",
              8: "Each WR points at its SGE.",
              9: "…and at the next WR: the linked list. Last WR's next = NULL.",
              10: "The remote side of the WRITE: the server's buffer address and rkey, learned in the handshake.",
              13: "One ibv_post_send call posts the whole list — one doorbell per K WRITEs.",
            },
          },
          diagram: "linked-list",
          explain: [
            "ibv_post_send takes a linked list of work requests, not one — that is the whole batching trick. The array wrs[64] is reused for every list; next pointers chain them; the last one ends at NULL.",
            "Each WR carries a scatter-gather element pointing at the local 1 MB buffer (addr + lkey), and — for RDMA WRITE — the remote address and rkey the server handed over during the handshake.",
          ],
          why: {
            adr: "0002",
            title: "Why one doorbell per K",
            text: "The doorbell write to the HCA is per ibv_post_send call. K WRs per call means 64× fewer doorbells — the naive T4 path posted one WR at a time, and the pipeline's small-size win (+37–67%) is the measured difference.",
          },
        },
        {
          id: "refill", title: "Refill — the SQ never empties",
          code: {
            file: "bw.c:900–916",
            lines: [
              "while (n > 0) {",
              "    uint64_t chunk = n < k ? n : k;",
              "    if (bw_refill(ctx, window, k, st)) return 1;",
              "    for (i = 0; i < chunk; ++i) {",
              "        uint64_t t = st->posted + i + 1;",
              "        ...build wrs[i]...",
              "    }",
              "    if (ibv_post_send(ctx->qp, &wrs[0], &bad_wr)) return 1;",
              "    st->posted += chunk; st->outstanding += chunk; n -= chunk;",
              "}",
            ],
            annotations: {
              1: "Post loop: one pass per K-WR list, until the size's count n is exhausted.",
              3: "Refill FIRST — reclaim ready CQEs while the window is full — then post. The SQ never drains to zero.",
              8: "One doorbell per list.",
              9: "Accounting: posted counts every WR (signal schedule); outstanding = posted − reclaimed.",
            },
          },
          diagram: "refill-live",
          explain: [
            "Refill is the discipline that replaces the template's wait-for-all: reclaim only the CQEs that are ready, then immediately repost. The template drained the SQ to zero every window and re-paid the ramp-up each time.",
            "The measured consequence (ADR-0005): +37–67% message rate at ≤ 64 B, no regression anywhere. At DMA sizes the naive path was already bus-saturated — the win is localized to where message rate binds.",
          ],
          whatif: {
            q: "What if we kept the template's wait-for-all pattern?",
            a: "Every window: drain to zero, idle ~an RTT, re-ramp. That was the T4 naive path — the A/B measured exactly this cost and found the refill's gain. Watch the panel: the refill keeps the fill level pinned at W.",
          },
        },
        {
          id: "remote", title: "Where the WRITE lands",
          code: {
            file: "bw.c:936–937",
            lines: [
              "wrs[i].wr.rdma.remote_addr = dest->buf_addr;",
              "wrs[i].wr.rdma.rkey = dest->rkey;",
            ],
            annotations: {
              1: "The server's buffer address — from the handshake message, where the server advertised it (plus rkey).",
              2: "The rkey proves the server's memory region permits remote writes. Without it the WRITE fails with a protection error.",
            },
          },
          diagram: "remote-write",
          explain: [
            "An RDMA WRITE is one-sided: the HCA reads the payload from the client's buffer (DMA read) and writes it into the server's registered memory at remote_addr — with no server CPU, no server context switch, nothing but the server's HCA.",
            "That is the point of the exercise: the server's data path is a buffer being filled. It cannot even see the data without asking the HCA.",
          ],
          why: {
            adr: "0003",
            title: "Why the assignment insists on the ack",
            text: "Because WRITE is one-sided, the client has no natural confirmation — the assignment's warning. The ack (a SEND, which the server's HCA can complete) is the only client-visible proof the data arrived.",
          },
        },
        {
          id: "inline", title: "Inline vs DMA",
          code: {
            file: "bw.c:906–907",
            lines: [
              "uint32_t inline_flag =",
              "        size <= ctx->max_inline_data ? IBV_SEND_INLINE : 0;",
            ],
            annotations: {
              1: "The boundary: messages ≤ the QP's max_inline_data (1024 B here) ride the WQE.",
              2: "max_inline_data is read back from the created QP — 'we asked the hardware, not a header' (ADR-0002).",
            },
          },
          diagram: "inline",
          explain: [
            "Small messages skip the DMA read: the payload rides inside the WQE itself at post time. One less host-memory read per message — at 6.1M msg/s that matters.",
            "Measured consequence (ADR-0004): the inline path carries a per-message payload copy at ~853 MB/s, capping ≤ 1 KB at ~6.55 Gbps — and the stack inlines small messages even without the flag. The 1 KB boundary on the envelope is exactly max_inline_data.",
          ],
          whatif: {
            q: "What if max_inline_data were larger?",
            a: "The copy plateau would extend to larger sizes — the measured limit is byte-for-byte the QP's max_inline_data (research ticket #12). On this hardware it is the cost of the small-message path.",
          },
        },
      ],
    },
  },
};
