/*
 * Teaching app — shared content model.
 *
 * Every stop carries the same four layers: concept / annotated code / ADR why /
 * viva what-ifs. The three prototype variants (A: field notes, B: system map,
 * C: viva deck) render this one model three structurally-different ways.
 *
 * Vocabulary follows CONTEXT.md. Code snippets are verbatim from bw.c with
 * inline comments elided where the gutter annotation carries them.
 */
window.APP = {
  title: "bw.c — follow the data",
  subtitle: "Verbs API throughput benchmark, end to end",

  home: {
    lead: "One client, one server, one queue pair, 21 message sizes. The client streams RDMA WRITEs into the server's registered memory and measures how fast they land — the clock runs from the first timed post until the server's ack arrives.",
    roles: [
      { who: "Client", what: "Drives everything: posts the WRITEs, starts and stops the clock, prints the 21 result lines." },
      { who: "Server", what: "Absorbs the WRITEs into its 1 MB buffer and acks each size's done. Its only data-path job." },
      { who: "The QP", what: "One Reliable Connected queue pair carries the data WRITEs AND the control messages (done / ack) as SENDs — the only QP in the program." },
      { who: "The window", what: "Up to W = 256 WRITEs outstanding at once, completions accounted in batches of K = 64. The pipe never drains." },
    ],
    highlights: [
      { value: "21", label: "sizes, 1 B to 1 MB, powers of two" },
      { value: "42.6", label: "Gbps peak (64 KB, mlxstud03/04)" },
      { value: "6.1M", label: "messages/s at small sizes" },
      { value: "W=256 · K=64", label: "the measured optimum (ADR-0006/0007)" },
    ],
  },

  /* The whole spine. state: 'built' (has a full stop) or 'planned'. */
  spine: [
    { id: "experiment", group: "Setup", title: "The experiment", state: "built" },
    { id: "handshake", group: "Setup", title: "The handshake", state: "planned" },
    { id: "memory-region", group: "Setup", title: "Memory region", state: "planned" },
    { id: "posting", group: "Data path", title: "Posting the window", state: "built" },
    { id: "doorbell", group: "Data path", title: "The doorbell", state: "planned" },
    { id: "wire", group: "Data path", title: "On the wire", state: "planned" },
    { id: "landing", group: "Data path", title: "Landing in server memory", state: "planned" },
    { id: "completions", group: "Data path", title: "Completions", state: "planned" },
    { id: "envelope", group: "The envelope", title: "The shape of the numbers", state: "planned" },
    { id: "audit", group: "Inside the audit", title: "What the audit found", state: "planned" },
    { id: "viva", group: "Viva", title: "Mock oral exam", state: "planned" },
  ],

  /* The measured envelope: means of 3 default sweeps, mlxstud03/04 (ADR-0007). */
  envelope: {
    unit: "Gbps",
    series: [
      { size: 0, bytes: 1, gbps: 0.049 },
      { size: 1, bytes: 2, gbps: 0.098 },
      { size: 2, bytes: 4, gbps: 0.196 },
      { size: 3, bytes: 8, gbps: 0.392 },
      { size: 4, bytes: 16, gbps: 0.784 },
      { size: 5, bytes: 32, gbps: 1.56 },
      { size: 6, bytes: 64, gbps: 2.62 },
      { size: 7, bytes: 128, gbps: 3.577 },
      { size: 8, bytes: 256, gbps: 5.84 },
      { size: 9, bytes: 512, gbps: 6.29 },
      { size: 10, bytes: 1024, gbps: 6.55 },
      { size: 11, bytes: 2048, gbps: 32.67 },
      { size: 12, bytes: 4096, gbps: 42.36 },
      { size: 13, bytes: 8192, gbps: 42.37 },
      { size: 14, bytes: 16384, gbps: 42.46 },
      { size: 15, bytes: 32768, gbps: 42.5 },
      { size: 16, bytes: 65536, gbps: 42.3 },
      { size: 17, bytes: 131072, gbps: 42.04 },
      { size: 18, bytes: 262144, gbps: 41.53 },
      { size: 19, bytes: 524288, gbps: 41.55 },
      { size: 20, bytes: 1048576, gbps: 40.57 },
    ],
  },

  stops: {
    experiment: {
      id: "experiment",
      title: "The experiment",
      subtitle: "What one size of the sweep measures, and where the clock sits",
      group: "Setup",
      adrs: ["0003"],
      concept: [
        "The benchmark is one number: how many bytes per second the client can push into the server's memory over one RC QP. It is measured once per size — 1 B through 1 MB, powers of two — because 'throughput' is not one number: at 1 B it is a message-rate story (6.1M messages/s), at 1 MB it is a wire story (40.6 Gbps).",
        "Each size is measured as two batches: a small warmup batch, then the timed batch whose elapsed time defines the number. The warmup rides the same windowed stream ahead of the timed batch so the pipe is already full when the clock starts.",
        "The clock (CLOCK_MONOTONIC) starts immediately before the first timed WRITE is posted and stops when the ack is received — the entire batch plus the control round trip is inside the measured window. Output is one ex1-identical line per size: size, throughput, unit.",
      ],
      terms: [
        { term: "Timed batch", def: "the MSG_COUNTS[i] WRITEs of one size whose elapsed time defines the throughput" },
        { term: "Warmup batch", def: "WARMUP_COUNTS[i] WRITEs sent before the timed batch, pipelined with it" },
        { term: "Size sweep", def: "the 21 sizes measured in one run, ascending; one warmup + timed batch per size" },
        { term: "Counts table", def: "per-size message counts inherited from ex1's convergence experiments (<1% variance between doubled counts)" },
        { term: "Done / Ack", def: "the two control SENDs per size: the done closes the timed batch, the ack carries the completion barrier back" },
        { term: "Sequence counter", def: "the size index 0–20 carried by both control messages; a mismatch means the exchange desynchronized" },
      ],
      code: {
        heading: "bw_client_bench — one size of the sweep",
        file: "bw.c:992–1021",
        lines: [
          "for (seq = 0; seq < SWEEP_SIZES; ++seq) {",
          "    size_t size = (size_t) 1 << seq;",
          "    uint64_t count = count_override ? count_override : MSG_COUNTS[seq];",
          "    struct bw_ctrl_msg done = { .tag = BW_CTRL_TAG, .seq = seq };",
          "",
          "    if (bw_post_writes(ctx, dest, size, WARMUP_COUNTS[seq],",
          "                       window, k, wrs, sges, &st, 0))",
          "        goto out;",
          "",
          "    clock_gettime(CLOCK_MONOTONIC, &t0);",
          "",
          "    if (bw_post_writes(ctx, dest, size, count,",
          "                       window, k, wrs, sges, &st, 1))",
          "        goto out;",
          "",
          "    if (bw_post_ctrl_send(ctx, BW_SEND_DONE_WRID, &done))",
          "        goto out;",
          "",
          "    if (bw_recv_ctrl(ctx,",
          "                     (1ull << BW_SEND_DONE_WRID) | (1ull << BW_DATA_WRID),",
          "                     seq, \"Ack\", &t1))",
          "        goto out;",
          "",
          "    elapsed = (double) (t1.tv_sec - t0.tv_sec) +",
          "              (double) (t1.tv_nsec - t0.tv_nsec) / 1e9;",
          "    bw_print_result(size, count, elapsed);",
          "}",
        ],
        annotations: {
          1: "21 sizes, ascending: size = 2^seq, so 2^0 = 1 B … 2^20 = 1 MB. seq doubles as the sequence counter.",
          2: "The counts table: ex1's converged numbers, verbatim (1 B: 1,310,720 WRITEs → 64 KB: 2560 → 1 MB: 80).",
          3: "The done control message — 8 bytes: tag + sequence counter. Sent on the data QP, never over TCP (ADR-0001).",
          5: "Warmup batch first: 4–32 WRITEs ride the stream ahead of the timed batch. It fills the pipe … at these counts, only partway — the audit's one methodology nuance.",
          8: "t0: the clock starts AFTER the warmup, immediately before the first timed post. Nothing before this counts.",
          10: "The timed batch: the WRITEs that define the number. Same windowed stream — the warmup and timed batches are one continuous pipe.",
          13: "The done SEND: 'all my timed WRITEs are posted'. RC in-order delivery means the server's done-receive completion proves every prior WRITE has landed.",
          15: "The ack wait: the clock stops HERE, at the ack's receive completion — not at the last post. The ack is the completion barrier (ADR-0003).",
          16: "While waiting for the ack, the data and done-send completions pass through — they precede the ack in the CQ, in order.",
          18: "Elapsed = ack time − first-post time: the whole batch plus the control round trip is inside the measured window.",
          20: "One ex1-identical line: size, throughput (auto-scaled bps → Gbps), nothing else. Byte-identical output to the TCP exercise.",
        },
      },
      why: [
        {
          adr: "ADR-0003",
          title: "Why the clock runs until the ack arrives",
          text: "A client-side completion only means the HCA sent the message — not that the server's memory holds it. Stopping the clock at the last WRITE post would measure the local enqueue rate, a different quantity, and the assignment's warning exists because students overstate throughput that way. The ack is a true completion barrier: it can only arrive after the server received the done, which in-order RC delivery guarantees came after every WRITE. Cost: one control round trip (~10 µs) added to every size — negligible above 1-byte, identical in shape for all.",
        },
        {
          adr: "ADR-0003",
          title: "Why it mirrors ex1 exactly",
          text: "The clock window is the same as the TCP exercise's ('the clock runs until the ACK arrives'), which keeps the output class-comparable: same methodology, same 21 lines, so the two exercises' numbers can sit side by side (and the IB numbers beat ex1's 1 GbE numbers ~7×).",
        },
        {
          adr: "ADR-0003",
          title: "A consequence: the server is on the client's clock",
          text: "Because the ack is inside the window, a slow server directly inflates every measurement. That is by design — it is what 'the message actually arrived' means — but it means the server's ack path is part of the measured quantity, and it is why the server acks each done before waiting for the next.",
        },
      ],
      whatifs: [
        {
          q: "What if the clock stopped at the last WRITE post instead?",
          a: "It would measure the local post rate, not the wire. At DMA sizes the enqueue rate outruns the link, so everything still in flight at t1 (up to W = 256 WRITEs, ~1.5 MB) would be counted as already delivered — the number would overstate the true rate by the inflight window's worth of bytes. The audit's rule of thumb: a completion means sent, not received.",
        },
        {
          q: "What if each side timed itself (two clocks)?",
          a: "You would measure a different quantity than ex1, and the two halves would need synchronization and a decision about where one ends and the other begins. Keeping one clock on the client, from first post to ack, reproduces ex1's methodology exactly — the property the assignment's output contract and ADR-0003 exist to preserve.",
        },
        {
          q: "What if there were no warmup batch?",
          a: "The pipe would start empty: the timed batch would spend its first ~256 WRITEs ramping the window up instead of saturating the wire. At 1 MB (80 WRITEs) the ramp would be the whole batch — the measured 1 MB dip is partly this arithmetic: rate = R·n/(n+4), 80/84 at n = 80, predicting 40.54 Gbps against the measured 40.57. The research ticket proposed a warmup ≥ W as an optimization lead (~1.76 Gbps recoverable at 1 MB).",
        },
        {
          q: "What if the ack were a TCP message instead?",
          a: "The done would be delivered out of order with respect to the WRITEs, so the ack could arrive while the last WRITEs are still on the wire — the clock would stop early and throughput would be overstated. That is why ADR-0001 chose SENDs on the data QP for both control messages.",
        },
      ],
    },

    posting: {
      id: "posting",
      title: "Posting the window",
      subtitle: "W = 256 outstanding, K = 64 signaled, the SQ never empties",
      group: "Data path",
      adrs: ["0002"],
      concept: [
        "The data path is a pipeline, not a loop that waits. The client keeps up to W = 256 WRITEs outstanding in the SQ — the window — and posts them in linked lists of K = 64 WRs per ibv_post_send call, so one doorbell covers 64 WRITEs instead of one per WRITE.",
        "Only every K-th WRITE is signaled (generates a CQE). Because RC completions are in-order, one CQE accounts for exactly K WRITEs — completions are counted in exact multiples of K, and 256/64 = 4 CQEs cover the whole window.",
        "The refill discipline sits between lists: while the window is full, poll the CQEs that are ready and reclaim their slots; then post the next list immediately. The SQ never drains to zero, so the NIC never idles. Messages ≤ max_inline_data ride the WQE inline (IBV_SEND_INLINE); larger ones are DMA-read from the single registered 1 MB buffer.",
      ],
      terms: [
        { term: "Window depth (W)", def: "how many outstanding WRs the SQ may hold; the pipeline never drains below it (default 256)" },
        { term: "Signal interval (K)", def: "every K-th WR generates a CQE; completions accounted in exact multiples of K (default 64)" },
        { term: "Refill", def: "reclaim only the CQEs that are ready, then immediately repost — the SQ never empties" },
        { term: "Inline", def: "message data rides inside the WQE at post time instead of being DMA-read from a buffer" },
        { term: "max_inline_data", def: "the device's inline limit, declared at QP creation and read back at runtime" },
      ],
      code: {
        heading: "bw_refill + bw_post_writes — the windowed stream",
        file: "bw.c:868–949",
        lines: [
          "/* bw_refill: reclaim ready CQEs while the window is full */",
          "while (st->outstanding >= window ||",
          "       st->outstanding + k >= (uint64_t) ctx->sq_depth) {",
          "    struct ibv_wc wc;",
          "    int ne = ibv_poll_cq(ctx->cq, 1, &wc);",
          "    if (ne == 0) continue;",
          "    if (bw_wc_bad(&wc, 1ull << BW_DATA_WRID)) return 1;",
          "    st->outstanding -= k;",
          "}",
          "",
          "/* bw_post_writes: post n WRITEs as K-WR linked lists */",
          "while (n > 0) {",
          "    uint64_t chunk = n < k ? n : k;",
          "    if (bw_refill(ctx, window, k, st)) return 1;",
          "    for (i = 0; i < chunk; ++i) {",
          "        uint64_t t = st->posted + i + 1;",
          "        uint32_t signal = (t % k == 0) ||",
          "                         (final && n == chunk && i == chunk - 1);",
          "        sges[i] = (struct ibv_sge) {",
          "            .addr = (uint64_t) ctx->buf, .length = size,",
          "            .lkey = ctx->mr->lkey };",
          "        wrs[i] = (struct ibv_send_wr) {",
          "            .wr_id = BW_DATA_WRID, .opcode = IBV_WR_RDMA_WRITE,",
          "            .send_flags = inline_flag | (signal ? IBV_SEND_SIGNALED : 0),",
          "            .sg_list = &sges[i], .num_sge = 1,",
          "            .next = i + 1 < chunk ? &wrs[i + 1] : NULL };",
          "        wrs[i].wr.rdma.remote_addr = dest->buf_addr;",
          "        wrs[i].wr.rdma.rkey = dest->rkey;",
          "    }",
          "    if (ibv_post_send(ctx->qp, &wrs[0], &bad_wr)) return 1;",
          "    st->posted += chunk; st->outstanding += chunk; n -= chunk;",
          "}",
        ],
        annotations: {
          1: "The refill runs at the head of every list post — never in the middle of the pipe.",
          2: "Window full (outstanding ≥ W) OR the SQ's device-clamped depth is close: keep room for the next K-WR list.",
          4: "Poll ONE CQE at a time — no batch reaping. The loop retries when the CQ is momentarily empty (WRITEs still in flight).",
          6: "One data CQE = exactly K WRs. This is the whole trick: in-order RC completions make the accounting exact.",
          9: "Each pass posts one linked list of up to K WRs. The last list takes the remainder (n % k WRs).",
          10: "Refill first, post next: the SQ never drains to zero — the NIC never idles. The template's wait-for-all pattern was rejected here (ADR-0002).",
          12: "t = this WR's position in the whole size stream (warmup + timed).",
          13: "Signal schedule: the K-th WR of the stream, plus the stream's very last WR (the remainder) — the final CQE the ack wait consumes.",
          16: "All WRITEs reference the same registered 1 MB buffer, never modified after init — no buffer-reuse hazard at full window depth.",
          18: "IBV_WR_RDMA_WRITE: the HCA reads from this buffer and writes straight into the server's memory, no server CPU.",
          21: "The remote address and rkey from the handshake — the server gave them over TCP before any data flowed.",
          23: "One ibv_post_send call = one doorbell for K WRITEs. This is what beat the naive path's +37–67% at small sizes (ADR-0005).",
        },
      },
      why: [
        {
          adr: "ADR-0002",
          title: "Why the refill replaces the template's wait-for-all",
          text: "The template's pp_wait_completions posts a window, waits for ALL of it, then reposts. Every window, the SQ drains to zero and the NIC idles for roughly a round trip, then re-pays the ramp-up. The refill-never-empty discipline polls only the CQEs that are ready and reposts immediately — the SQ holds the window continuously, and the measured gain at ≤ 64 B was +37–67% in message rate. The user's viva line: 'we asked the hardware, not the header'.",
        },
        {
          adr: "ADR-0002",
          title: "Why K = 64 signals instead of every WRITE",
          text: "Fewer CQEs means less poll pressure in the refill — one CQE per K WRs instead of one per WRITE — and the accounting stays exact because RC completions are in-order: CQE #j covers WRs j·K−K+1…j·K, no bookkeeping needed. K is bounded by the window and by QP_SLACK so the done SEND always finds a free SQ slot.",
        },
        {
          adr: "ADR-0002",
          title: "Why one 1 MB buffer, never modified",
          text: "A window of 256 outstanding WRITEs means the last posted WRITE's buffer must still be valid when its completion lands. With a single registered buffer that is never written after init, there is no reuse hazard and no buffer cycling — the classic RDMA bug the design simply removes.",
        },
        {
          adr: "ADR-0002",
          title: "Why inline ≤ max_inline_data, declared then read back",
          text: "Small messages ride the WQE itself instead of being DMA-read — one less read from host memory per message. The limit is discovered the robust way: declare max_inline_data at QP creation (stepping down 1024 → 0 until mlx4 accepts) and read the created value back via ibv_query_qp — 'we asked the hardware, not a header'.",
        },
      ],
      whatifs: [
        {
          q: "What if we signaled every WRITE (K = 1)?",
          a: "Four times the CQE pressure in the refill, exact accounting retained. The T6 A/B measured it: (256,128) and (512,128) land within 0.1% of the default at every anchor size — the CQE rate is simply not a factor at these window depths. The naive T4 path, which posted one WRITE per doorbell and waited for all completions, was already bus-saturated at DMA sizes (ADR-0005).",
        },
        {
          q: "What if we used the template's wait-for-all pattern?",
          a: "Each window would drain to zero and idle for ~an RTT, then re-pay the ramp-up. That is exactly the T4 naive path, and the A/B measured the pipeline's win: +37–67% message rate at ≤ 64 B, identical elsewhere. The refill's gain is real and localized to the small sizes where message rate is the binding constraint.",
        },
        {
          q: "What if W were too small to cover the RTT × bandwidth product?",
          a: "The pipe could not stay full — the wire would go quiet every window. The T6 A/B pushed W to 512 and measured no change, and even the naive path saturated the bus, so 256 is deep enough on this hardware. The honest viva answer: W = 256 was the assumed default; the measurement campaign confirmed it is the optimum (ADR-0006/0007).",
        },
        {
          q: "What if max_inline_data were bigger (or we didn't declare it)?",
          a: "The inline path carries a per-message payload copy at ~853 MB/s (measured, ADR-0004), which caps messages ≤ max_inline_data at ~6.4–6.55 Gbps. A bigger limit would extend the copy plateau to bigger sizes; without the declaration, the stack still inlines small messages anyway — the measured envelope is identical with and without the flag. The boundary at 1 KB is exactly max_inline_data (research ticket #12).",
        },
      ],
    },
  },
};
